/*!
*  MIT License
*  
*  Copyright (c) 2020 ericyonng<120453674@qq.com>
*  
*  Permission is hereby granted, free of charge, to any person obtaining a copy
*  of this software and associated documentation files (the "Software"), to deal
*  in the Software without restriction, including without limitation the rights
*  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*  copies of the Software, and to permit persons to whom the Software is
*  furnished to do so, subject to the following conditions:
*  
*  The above copyright notice and this permission notice shall be included in all
*  copies or substantial portions of the Software.
*  
*  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
*  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
*  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
*  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
*  SOFTWARE.
* 
* Author: Eric Yonng
* Description: Generated By protogentool, Dont Modify This File!!!
*/


#include "pch.h"
#include <protocols/cplusplus/com_passtime.pb.h>
#include <protocols/orm_out/PassTimeDataOrmData.h>

SERVICE_COMMON_BEGIN

PassTimeDataOrmData::PassTimeDataOrmData()
:_ormRawPbData(new ::CRYSTAL_NET::service::PassTimeData)
{
}

PassTimeDataOrmData::PassTimeDataOrmData(::CRYSTAL_NET::service::PassTimeData *pb)
:_ormRawPbData(NULL)
{
    AttachPb(pb);
}

PassTimeDataOrmData::PassTimeDataOrmData(const PassTimeDataOrmData &other)
:IOrmData(reinterpret_cast<const IOrmData &>(other))
,_ormRawPbData(other._ormRawPbData ? new ::CRYSTAL_NET::service::PassTimeData(*other._ormRawPbData) : NULL)
{
    SetAttachPbFlag(false);
}

PassTimeDataOrmData::PassTimeDataOrmData(PassTimeDataOrmData &&other)
:IOrmData(std::forward<IOrmData>(other))
,_ormRawPbData(other._ormRawPbData)
{
    other._ormRawPbData = NULL;
}

PassTimeDataOrmData::PassTimeDataOrmData(const ::CRYSTAL_NET::service::PassTimeData &pb)
:_ormRawPbData(new ::CRYSTAL_NET::service::PassTimeData(pb))
{

}

PassTimeDataOrmData::~PassTimeDataOrmData()
{
    if(LIKELY(!IsAttachPb()))
        CRYSTAL_RELEASE_SAFE(_ormRawPbData);
}

void PassTimeDataOrmData::Release()
{
    PassTimeDataOrmData::DeleteThreadLocal_PassTimeDataOrmData(this);
}

PassTimeDataOrmData &PassTimeDataOrmData::operator =(const ::CRYSTAL_NET::service::PassTimeData &pb)
{
    if(LIKELY(!IsAttachPb()))
        CRYSTAL_RELEASE_SAFE(_ormRawPbData);

    SetAttachPbFlag(false);
    _ormRawPbData = new ::CRYSTAL_NET::service::PassTimeData(pb);
    _MaskDirty(true);
    return *this;
}

PassTimeDataOrmData &PassTimeDataOrmData::operator =(const PassTimeDataOrmData &other)
{
    if(this == &other)
        return *this;

    IOrmData::operator =(reinterpret_cast<const IOrmData &>(other));
    if(LIKELY(!IsAttachPb()))
        CRYSTAL_RELEASE_SAFE(_ormRawPbData);

    _ormRawPbData = NULL;
    SetAttachPbFlag(false);
    if(other._ormRawPbData)
        _ormRawPbData = new ::CRYSTAL_NET::service::PassTimeData(*other._ormRawPbData);
    _MaskDirty(true);

    return *this;
}

PassTimeDataOrmData &PassTimeDataOrmData::operator =(PassTimeDataOrmData &&other)
{
    if(this == &other)
        return *this;

    IOrmData::operator =(std::forward<IOrmData>(other));
    _ormRawPbData = other._ormRawPbData;
    other._ormRawPbData = NULL;


    return *this;
}

void PassTimeDataOrmData::Clear()
{

    if(_ormRawPbData)
        _ormRawPbData->Clear();

    _MaskDirty(true);
}

void PassTimeDataOrmData::_AttachPb(void *pb)
{
    if(LIKELY(!IsAttachPb()))
        CRYSTAL_RELEASE_SAFE(_ormRawPbData);

    _ormRawPbData = reinterpret_cast<::CRYSTAL_NET::service::PassTimeData *>(pb);


}

KERNEL_NS::LibString PassTimeDataOrmData::ToJsonString() const
{
    return _ormRawPbData->ToJsonString();
}

bool PassTimeDataOrmData::ToJsonString(std::string *data) const
{
    return _ormRawPbData->ToJsonString(data);
}

bool PassTimeDataOrmData::FromJsonString(const Byte8 *data, size_t len)
{
    return _ormRawPbData->FromJsonString(data, len);
}

const ::CRYSTAL_NET::service::PassTimeData *PassTimeDataOrmData::GetPbRawData() const
{
    return _ormRawPbData;
}

void PassTimeDataOrmData::clear_lastpassdaytime()
{
    _ormRawPbData->clear_lastpassdaytime();
    _MaskDirty(true);
}

int64_t PassTimeDataOrmData::lastpassdaytime() const
{
    return _ormRawPbData->lastpassdaytime();
}

void PassTimeDataOrmData::set_lastpassdaytime(int64_t value)
{
    _ormRawPbData->set_lastpassdaytime(value);
    _MaskDirty(true);
}

bool PassTimeDataOrmData::_OnEncode(KERNEL_NS::LibStream<KERNEL_NS::_Build::MT> &stream) const
{
    return _ormRawPbData->Encode(stream);
}

bool PassTimeDataOrmData::_OnEncode(KERNEL_NS::LibStream<KERNEL_NS::_Build::TL> &stream) const
{
    return _ormRawPbData->Encode(stream);
}

bool PassTimeDataOrmData::_OnDecode(KERNEL_NS::LibStream<KERNEL_NS::_Build::MT> &stream)
{
    return _ormRawPbData->Decode(stream);
}

bool PassTimeDataOrmData::_OnDecode(KERNEL_NS::LibStream<KERNEL_NS::_Build::TL> &stream)
{
    return _ormRawPbData->Decode(stream);
}

IOrmData *PassTimeDataOrmDataFactory::Create() const
{
    return PassTimeDataOrmData::NewThreadLocal_PassTimeDataOrmData();
}


SERVICE_COMMON_END
