version: 1.0.7.{build}
max_jobs: 8
branches:
    only:
        - main

clone_depth: 50
clone_folder: c:\projects\crystalnet
install:
    - cmd: >-
        git submodule update --init --recursive
        
        echo 2022 | call winsolution_build.bat 0
        
image: Visual Studio 2022
configuration: 
    - Debug
    - Release
platform: x64
for:
-
    matrix:
        exclude:
            - configuration: Debug
              platform: x86
              
            - configuration: Release
              platform: x86

build:
    verbosity: normal
    project: .\build\vs2022\CrystalNet_vs2022.sln
    
notifications:
- provider: Email
  to:
  - 120453674@qq.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false    
