/*!
*  MIT License
*  
*  Copyright (c) 2020 ericyonng<120453674@qq.com>
*  
*  Permission is hereby granted, free of charge, to any person obtaining a copy
*  of this software and associated documentation files (the "Software"), to deal
*  in the Software without restriction, including without limitation the rights
*  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*  copies of the Software, and to permit persons to whom the Software is
*  furnished to do so, subject to the following conditions:
*  
*  The above copyright notice and this permission notice shall be included in all
*  copies or substantial portions of the Software.
*  
*  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
*  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
*  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
*  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
*  SOFTWARE.
* 
* Author: Eric Yonng
* Description: Generated By protogentool_debug, Dont Modify This File!!!
*/


export namespace crystal_net_service
{

    // com_book.proto
    export enum BookType_ENUMS {
        UNKNOWN = 0,

    }
    // com_library.proto
    export enum BorrowOrderState_ENUMS {
        // 待出库
        WAITING_OUT_OF_WAREHOUSE = 0,
        // 订单已出库等待领取
        WAIT_USER_RECEIVE = 1,
        // 用户已领取等待归还
        WAIT_USER_RETURN_BACK = 2,
        // 取消订单(需要填写原因, 当用户领取后不可取消订单只能归还, 还没领取的才可取消订单)
        CANCEL_ORDER = 3,
        // 已归还
        RETURN_BAKCK = 4,

    }
    // com_library.proto
    export enum CancelOrderReasonType_ENUMS {
        UNKNOWN = 0,
        // 等用户领取超时
        WAIT_USER_GET_TIME_OUT = 1,
        // 管理员取消订单(管理员需要填写理由)
        MANAGTER_CANCEL = 2,
        // 用户自己取消订单
        USER_SELF_CANCEL = 3,

    }
    // com_notify.proto
    export enum ClearNotifyType_ENUMS {
        // 只清理已读
        OnlyRead = 0,
        // 清理全部
        ClearAll = 1,

    }
    // com_client_user.proto
    export enum ClientUserStatus_ENUMS {
        // 未登录
        UNLOGIN = 0,
        // 登录中
        LOGINING = 1,
        // 登录完成
        LOGINED = 2,
        // 登录结束
        CLIENT_LOGIN_ENDING = 3,
        // 登陆结束的结束
        CLIENT_LOGIN_ENDING_FINISH = 4,
        // 登出中(定时15秒切换状态)
        LOGOUTING = 5,
        // 登出完成
        LOGOUTED = 6,

    }
    // com.proto
    export enum CreatureAttrKey_ENUM {
        BEGIN = 0,
        Atk = 1,
        Def = 2,
        HpLmt = 3,
        HpRcv = 4,
        Cure = 5,
        AngerLmt = 6,
        AngerRcv = 7,
        Anger = 8,
        Hp = 9,
        MoveSpd = 10,
        ActSpd = 11,
        MMoveSpd = 12,
        MActSpd = 13,
        ExtraHp = 14,
        VMoveSpd = 15,
        //VActSpd = 16; // 载具动画速率
        BuffHp = 17,
        BuffHpLmt = 18,
        BuffHpBloodSpeed = 19,
        Crit = 101,
        Res = 102,
        Hit = 103,
        Prr = 104,
        Ddg = 105,
        Crid = 106,
        Crrd = 107,
        Critv = 108,
        Resv = 109,
        Hitv = 110,
        Prrv = 111,
        Ddgv = 112,
        AtkAdd = 151,
        DefAdd = 152,
        HpLmtAdd = 153,
        Pedm = 201,
        Prdm = 202,
        Medm = 203,
        Mrdm = 204,
        Sedm = 205,
        Srdm = 206,
        Ardm = 210,
        Lv = 251,
        AwakeLv = 252,
        ExpLmt = 253,
        Exp = 254,
        ExpMul = 255,
        ExpAdd = 256,
        GoldMul = 257,
        DoubleExp = 258,
        VipLv = 270,
        Forces = 299,

    }
    // com_user.proto
    export enum LoginMode_ENUMS {
        // 使用密码登录
        PASSWORD = 0,
        // 使用登录令牌登录
        USE_LOGIN_TOKEN = 1,
        // 注册登录
        REGISTER = 2,

    }
    // com_user.proto
    export enum LogoutReason_ENUMS {
        // 其他地方登录
        LOGIN_OTHER_PLACE = 0,
        // 其他原因
        OTHER_REASON = 1,
        // 玩家主动退登
        USER_LOGOUT = 2,
        // 空闲
        USER_IDLE = 3,
        // 超时
        TIMEOUT = 4,
        // 关服
        CLOSE_SERVER = 5,
        // 登录其他账号
        LOG_IN_OTHER_ACCOUNT = 6,

    }
    // com_heartbeat.proto
    export enum NODE_IPTYPE_TYPE_ENUMS {
        IPV4 = 0,
        IPV6 = 1,

    }
    // com_offline.proto
    export enum OfflineType_ENUMS {
        // 未知
        UNKNOWN = 0,
        // 通知
        NOTIFY = 1,

    }
    // com_library.proto
    export enum OperationType_ENUMS {
        // 未知
        UNKNOWN = 0,

    }
    // com_library.proto
    export enum RoleType_ENUMS {
        // 无权限
        NoAuth = 0,
        // 普通成员
        NormalMember = 1,
        // 管理员
        Manager = 2,
        // 馆长
        Librarian = 3,

    }
    // com_variant.proto
    export enum VariantParamType_ENUMS {
        // 未知
        UNKNOWN = 0,
        // 字符串
        STRING = 1,
        // 有符号整数
        VALUE = 2,
        // 无符号整数
        UNSIGNED_VALUE = 3,
        // 浮点数
        DOUBLE_VALUE = 4,

    }
    // 书籍数量
    /// Opcode:
    // library.proto
    export class AddLibraryBookCountReq {
        // 图书的id
        BookId:number = 0;

        // 修改数量
        ModifyCount:number = 0;


    }
    // 书籍数量
    /// Opcode:
    // library.proto
    export class AddLibraryBookCountRes {
        ErrCode:number = 0;


    }
    // 录书
    /// Opcode:
    // library.proto
    export class AddLibraryBookReq {
        // 书名
        BookName:string = "";

        // isbn
        IsbnCode:string = "";

        BookCoverImage?:string;

        // 价格(单位分)
        Price:number = 0;

        // 数量 增量
        ModifyCount:number = 0;

        KeyWords?:KeyWordsField;

        Content?:string;

        Snapshot?:SnapshotField;


    }
    // 录书结果
    /// Opcode:
    // library.proto
    export class AddLibraryBookRes {
        ErrCode:number = 0;


    }
    // 新增通知数据
    /// Opcode:
    // notify.proto
    export class AddUserNotifyDataItemNty {
        ItemList:UserNotifyDataItem[] = [];


    }
    // 背包数据
    // com_bookbag.proto
    export class BookBagInfo {
        BookInfoItemList:BookInfoItem[] = [];


    }
    // 书包数据
    /// Opcode:
    // bookbag.proto
    export class BookBagInfoNty {
        BookBagInfo:BookBagInfo = new BookBagInfo();

        // 图书列表
        BookInfoList:BookInfo[] = [];


    }
    // 书包数据请求
    /// Opcode:
    // bookbag.proto
    export class BookBagInfoReq {

    }
    // 书包数据请求
    /// Opcode:
    // bookbag.proto
    export class BookBagInfoRes {
        ErrCode:number = 0;


    }
    // 书籍信息, 数据存储:id, isbn(unique), bookInfo json 查书通过上拉显示下一页
    // com_book.proto
    export class BookInfo {
        // 唯一id, 同一个isbn, 同一个id
        Id:number = 0;

        // 图书类型 BookType
        BookType:number = 0;

        // 书名
        BookName:string = "";

        // 书isbn码
        IsbnCode:string = "";

        // 封面
        BookCoverImage:string = "";

        // 是否上架
        IsOnShelves:number = 0;

        // 可变数据
        VariantInfo:BookVariantInfo = new BookVariantInfo();

        // 被借数量
        BorrowedCount:number = 0;

        // 关键词
        KeyWords:string[] = [];

        // 内容简介 最多10KB左右
        Content:string = "";

        // 截图最多9张
        Snapshot:string[] = [];

        // 客户端使用
        CoverImagePath:string = "";

        KeywordsString:string = "";

        SnapshotPreivewInfoList:SnapshotClientInfo[] = [];


    }
    // 背包中的图书信息
    // com_bookbag.proto
    export class BookInfoItem {
        // 图书id
        BookId:number = 0;

        // 图书数量
        BookCount:number = 0;

        // 借的天数
        BorrowDays:number = 0;


    }
    // 图书列表数据
    /// Opcode:
    // library.proto
    export class BookListNty {
        BookInfoList:BookInfo[] = [];


    }
    // 图书类型
    // com_book.proto
    export class BookType {

    }
    // 图书可变数据
    // com_book.proto
    export class BookVariantInfo {
        // 库存数量
        Count:number = 0;

        // 价格(单位分)
        Price:number = 0;


    }
    // 图书可变数据
    // com_book.proto
    export class BookVariantInfoItem {
        // 图书id
        Id:number = 0;

        BookVariantInfo:BookVariantInfo = new BookVariantInfo();


    }
    // 图书数量变更
    /// Opcode:
    // library.proto
    export class BookVariantInfoItemsNty {
        BookVariantInfoItemList:BookVariantInfoItem[] = [];


    }
    // 图书数据变更
    /// Opcode:
    // library.proto
    export class BooksChangeNty {
        BookInfoList:BookInfo[] = [];


    }
    // 图书详情信息
    // com_library.proto
    export class BorrowBookDetailInfo {
        BookInfo:BorrowBookInfo = new BorrowBookInfo();

        BookName:string = "";


    }
    // 当 ReturnBackCount == BorrowCount时表示还完
    // com_library.proto
    export class BorrowBookInfo {
        // book id
        BookId:number = 0;

        // isbn码
        IsbnCode:string = "";

        // 借阅数量
        BorrowCount:number = 0;

        // 借阅时间
        BorrowTime:number = 0;

        // 预计归还时间(领取后算起) TODO:
        PlanGiveBackTime:number = 0;

        // 实际归还时间
        RealGiveBackTime:number = 0;

        // 已还数量
        ReturnBackCount:number = 0;

        // 子单号(当前借的书的单号)
        SubOrderId:number = 0;

        // 要借的天数
        BorrowDays:number = 0;


    }
    // 订单详情
    // com_library.proto
    export class BorrowOrderDetailInfo {
        // 订单号
        OrderId:number = 0;

        // 借的书
        BorrowBookList:BorrowBookDetailInfo[] = [];

        // 订单创建时间
        CreateOrderTime:number = 0;

        // 订单状态 BorrowOrderState
        OrderState:number = 0;

        // 取消原因
        CancelReason:CancelOrderReason = new CancelOrderReason();

        // 领取超时时间(出库后一到两天内领取),超过后自动取消订单 TODO:
        GetOverTime:number = 0;

        // 备注
        Remark:string = "";

        // 用户id
        UserId:number = 0;

        // 用户昵称
        Nickname:string = "";


    }
    // 借还订单信息
    // com_library.proto
    export class BorrowOrderInfo {
        // 订单号
        OrderId:number = 0;

        // 借的书
        BorrowBookList:BorrowBookInfo[] = [];

        // 订单创建时间
        CreateOrderTime:number = 0;

        // 订单状态 BorrowOrderState
        OrderState:number = 0;

        // 取消原因
        CancelReason:CancelOrderReason = new CancelOrderReason();

        // 领取超时时间(出库后一到两天内领取),超过后自动取消订单 TODO:
        GetOverTime:number = 0;

        // 备注
        Remark:string = "";

        // 用户id
        UserId:number = 0;


    }
    // 订单状态
    // com_library.proto
    export class BorrowOrderState {

    }
    // com_library.proto
    export class CancelOrderReason {
        // 原因code
        CancelReason:number = 0;

        // 具体原因内容
        CancelInfo:string = "";


    }
    // com_library.proto
    export class CancelOrderReasonType {

    }
    // 取消订单(管理员或者用户自己取消订单)
    /// Opcode:
    // library.proto
    export class CancelOrderReq {
        // 订单id
        OrderId:number = 0;

        // 原因(管理员必须填写)
        Reason:string = "";


    }
    // 取消订单(管理员或者用户自己取消订单)
    /// Opcode:
    // library.proto
    export class CancelOrderRes {
        ErrCode:number = 0;


    }
    // com_notify.proto
    export class ClearNotifyType {

    }
    // 客户端的心跳
    /// Opcode:, NoLog:true, XorEncrypt:true, KeyBase64:true
    // heartbeat.proto
    export class ClientHeartbeatReq {

    }
    /// Opcode:, NoLog:true
    // heartbeat.proto
    export class ClientHeartbeatRes {
        // 服务器时间
        ServerTimeMs:number = 0;


    }
    // com_client_user.proto
    export class ClientUserInfo {
        // uid
        UserId:number = 0;

        // 账号
        AccountName:string = "";

        // 姓名
        Name:string = "";

        // 昵称
        Nickname:string = "";

        // 手机设备imei
        PhoneImei:string = "";

        // 登录状态 ClientUserStatus
        ClientStatus:number = 0;

        // token
        LastToken:string = "";

        // token过期时间
        TokenExpireTime:number = 0;

        // 绑定手机
        BindPhone:number = 0;


    }
    // com_client_user.proto
    export class ClientUserStatus {

    }
    /// Opcode:
    // library.proto
    export class CreateLibraryReq {
        // 邀请码
        InviteCode:string = "";

        // 管名
        Name:string = "";

        // 书馆地址
        Address:string = "";

        // 书馆经营时间
        OpenTime:string = "";

        // 书馆联系电话
        TelphoneNumber:string = "";

        // 必须绑定手机号
        BindPhone:number = 0;


    }
    /// Opcode:
    // library.proto
    export class CreateLibraryRes {
        ErrCode:number = 0;


    }
    // 属性类型枚举
    // com.proto
    export class CreatureAttrKey {

    }
    // 按照书名或者关键字查询
    /// Opcode:
    // library.proto
    export class GetBookByBookNameReq {
        BookName:string = "";


    }
    // 按照书名查询
    /// Opcode:
    // library.proto
    export class GetBookByBookNameRes {
        BookInfoList:BookInfo[] = [];


    }
    // 分页查询图书
    /// Opcode:
    // library.proto
    export class GetBookInfoListReq {
        // 基准图书id
        BaseBookId:number = 0;

        // 数量 负数表示 BaseBookId 之前的前n个图书信息, 整数表示 BaseBookId 之后n个图书信息
        BookCount:number = 0;


    }
    // 分页查询图书
    /// Opcode:
    // library.proto
    export class GetBookInfoListRes {
        BookInfoList:BookInfo[] = [];


    }
    // 查图书信息
    /// Opcode:
    // library.proto
    export class GetBookInfoReq {
        IsbnCode:string = "";


    }
    // 查图书信息
    /// Opcode:
    // library.proto
    export class GetBookInfoRes {
        ErrCode:number = 0;

        // 图书
        BookInfo:BookInfo = new BookInfo();


    }
    // 获取图书列表
    /// Opcode:
    // library.proto
    export class GetBookListReq {

    }
    // 图书数据请求
    /// Opcode:
    // library.proto
    export class GetBookListRes {
        ErrCode:number = 0;


    }
    // 查询图书订单信息
    /// Opcode:
    // library.proto
    export class GetBookOrderDetailInfoNty {
        DetailInfo:BorrowOrderDetailInfo[] = [];


    }
    // 查询图书订单信息
    /// Opcode:
    // library.proto
    export class GetBookOrderDetailInfoReq {

    }
    // 查询图书订单信息
    /// Opcode:
    // library.proto
    export class GetBookOrderDetailInfoRes {
        ErrCode:number = 0;


    }
    /// Opcode:
    // library.proto
    export class GetLibraryInfoReq {

    }
    /// Opcode:
    // library.proto
    export class GetLibraryInfoRes {
        ErrCode:number = 0;


    }
    // 获取图书馆列表
    /// Opcode:
    // library.proto
    export class GetLibraryListReq {

    }
    // 获取图书馆列表
    /// Opcode:
    // library.proto
    export class GetLibraryListRes {
        LibraryPreviewInfoList:LibraryPreviewInfo[] = [];


    }
    // 获取用户信息
    /// Opcode:
    // library.proto
    export class GetLibraryMemberSimpleInfoReq {

    }
    // 获取用户信息
    /// Opcode:
    // library.proto
    export class GetLibraryMemberSimpleInfoRes {
        ErrCode:number = 0;

        SimpleUserInfoList:SimpleUserInfo[] = [];


    }
    /// Opcode:
    // heartbeat.proto
    export class GetNodeListReq {
        // 集群名
        ClusterName:string = "";

        // 关心的节点服务名列表
        CareNodeServiceNameList:string[] = [];


    }
    /// Opcode:
    // heartbeat.proto
    export class GetNodeListRes {
        NodeInfoList:NodeHeartbeatInfo[] = [];


    }
    // 加入图书馆: 不在图书馆内,
    /// Opcode:
    // library.proto
    export class JoinLibraryReq {
        LibraryId:number = 0;


    }
    // 加入图书馆:刚开始是无权限的, 只有让管理员添加成为会员才有权限借阅
    /// Opcode:
    // library.proto
    export class JoinLibraryRes {
        ErrCode:number = 0;


    }
    // 关键词
    // com_library.proto
    export class KeyWordsField {
        KeyWords:string[] = [];


    }
    // 管理员信息(包含馆长)
    // com_library.proto
    export class LibararyManagerInfo {
        // 管理员id
        UserId:number = 0;


    }
    // com_library.proto
    export class LibraryInfo {
        // 唯一id
        Id:number = 0;

        // 图书馆名
        Name:string = "";

        // 图书馆地址
        Address:string = "";

        // 图书馆经营时间
        OpenTime:string = "";

        // 图书馆联系电话
        TelphoneNumber:string = "";

        // 馆长id
        LibrarianUserId:number = 0;

        // 馆长名
        LibrarianUserNickname:string = "";

        // 管理员列表
        ManagerInfoList:LibararyManagerInfo[] = [];

        // 会员列表
        MemberList:MemberInfo[] = [];

        // 书不直接推送详情下去 TODO:
        BookList:BookInfo[] = [];


    }
    // 图书馆信息, 登录成功后主动推送
    /// Opcode:
    // library.proto
    export class LibraryInfoNty {
        LibraryInfo:LibraryInfo = new LibraryInfo();


    }
    // 图书馆预览数据
    // com_library.proto
    export class LibraryPreviewInfo {
        // 图书馆id
        Id:number = 0;

        // 图书馆名
        Name:string = "";

        // 馆长id
        LibrarianUserId:number = 0;

        // 馆长昵称
        LibrarianNickname:string = "";


    }
    /// Opcode:
    // login.proto
    export class LoginFinishReq {

    }
    /// Opcode:
    // login.proto
    export class LoginFinishRes {
        ErrCode:number = 0;


    }
    // 登录信息
    // com_user.proto
    export class LoginInfo {
        // 登录模式
        LoginMode:number = 0;

        // 账号
        AccountName:string = "";

        // 密码
        Pwd:string = "";

        // 登录令牌
        LoginToken:string = "";

        // 登录设备
        LoginPhoneImei:string = "";

        // 登录目标ip
        TargetIp:string = "";

        // 登录目标端口
        Port:number = 0;

        UserRegisterInfo?:RegisterUserInfo;

        // 鉴权:ip是黑白校验, 设备黑白校验, 账号黑白校验
        // 产品id
        AppId:string = "";

        // 密文
        cypherText:string = "";

        // 原文
        originText:string = "";

        // 版本号
        versionId:number = 0;


    }
    /// Opcode:
    // login.proto
    export class LoginInfoNty {
        // 更新登录token
        Token:string = "";

        // 过期时间(秒级时间戳)
        KeyExpireTime:number = 0;


    }
    // 登录模式
    // com_user.proto
    export class LoginMode {

    }
    /// Opcode:, XorEncrypt:true, KeyBase64:true
    // login.proto
    export class LoginReq {
        LoginUserInfo:LoginInfo = new LoginInfo();


    }
    /// Opcode:
    // login.proto
    export class LoginRes {
        errCode:number = 0;

        UserId:number = 0;

        // 毫秒级
        ServerTime:number = 0;


    }
    /// Opcode:
    // login.proto
    export class LogoutNty {
        // LogoutReason
        LogoutReason:number = 0;

        // 告知最后登陆的ip
        ip:string = "";


    }
    // com_user.proto
    export class LogoutReason {

    }
    /// Opcode:
    // login.proto
    export class LogoutReq {

    }
    // 用户领书管理员扫码
    /// Opcode:
    // library.proto
    export class ManagerScanOrderForUserGettingBooksReq {
        // 订单id
        OrderId:number = 0;


    }
    // 用户领书管理员扫码
    /// Opcode:
    // library.proto
    export class ManagerScanOrderForUserGettingBooksRes {
        ErrCode:number = 0;


    }
    // 会员信息(包括管理员等)
    // com_library.proto
    export class MemberInfo {
        // user id
        UserId:number = 0;

        // 角色 RoleType
        Role:number = 0;

        // 会员昵称
        Nickname:string = "";

        // 当前借阅图书列表 只有有权限的人才会看到订单详情, 其他人只能看自己的, 避免被恶意下单, 最多一天借100本书 TODO:
        BorrowList:BorrowOrderInfo[] = [];

        // 锁定操作超时时间
        LockTimestampMs:number = 0;

        BindPhone?:number;


    }
    // 修改权限 馆长不可修改自己的权限, 只能转让, 管理员不可以将自己升级, 只能管理员修改权限 TODO:
    /// Opcode:
    // library.proto
    export class ModifyMemberInfoReq {
        memberUserId:number = 0;

        newRole?:number;

        newMemberPhone?:number;


    }
    /// Opcode:
    // library.proto
    export class ModifyMemberInfoRes {
        ErrCode:number = 0;


    }
    /// Opcode:
    // player.proto
    export class ModifyPlayerNameReq {
        newName:string = "";


    }
    /// Opcode:
    // player.proto
    export class ModifyPlayerNameRes {
        errCode:number = 0;


    }
    // 修改密码
    // user.proto
    export class ModifyPwdInfo {
        OldPwd:string = "";

        NewPwd:string = "";


    }
    // 修改用户信息 TODO:
    /// Opcode:
    // user.proto
    export class ModifyUserInfoReq {
        // 修改密码
        PwdInfo?:ModifyPwdInfo;

        // 修改昵称
        Nickname?:string;


    }
    // 修改用户信息
    /// Opcode:
    // user.proto
    export class ModifyUserInfoRes {
        ErrCode:number = 0;


    }
    // com_heartbeat.proto
    export class NODE_IPTYPE {

    }
    // 服务器节点间的心跳信息
    // com_heartbeat.proto
    export class NodeHeartbeatInfo {
        // 服务名
        ServiceName:string = "";

        // ip
        address:string = "";

        // ip类型
        IpType:number = 0;

        // 开放的互联端口
        InnerLinkPort:number = 0;

        // 监听的协议列表
        SubscribeOpcodes:number[] = [];

        // api列表
        ApiList:string[] = [];


    }
    /// Opcode:, NoLog:true
    // heartbeat.proto
    export class NodeHeartbeatReq {

    }
    /// Opcode:, NoLog:true
    // heartbeat.proto
    export class NodeHeartbeatRes {
        // 当前服务器对时
        NowTimeNanoseconds:number = 0;


    }
    // 离线数据: id => OfflineData
    // com_offline.proto
    export class OfflineData {
        // 离线类型
        OfflineType:number = 0;

        // 用户id
        UserId:number = 0;

        // 离线数据
        OfflineData:string = "";

        // 时间(毫秒)
        CreateTime:number = 0;


    }
    // 离线类型
    // com_offline.proto
    export class OfflineType {

    }
    // 一键清理通知
    /// Opcode:
    // notify.proto
    export class OnekeyClearNotifyReq {
        // 清理类型 ClearNotifyType
        ClearType:number = 0;


    }
    // 一键清理通知
    /// Opcode:
    // notify.proto
    export class OnekeyClearNotifyRes {
        ErrCode:number = 0;


    }
    // 操作日志
    // com_library.proto
    export class OperationLogInfo {
        OpType:number = 0;

        OpUserId:number = 0;

        OpNickname:string = "";

        Role:number = 0;

        OpTimeMs:number = 0;

        Params:VariantParam[] = [];


    }
    // com_library.proto
    export class OperationType {

    }
    // 出库
    /// Opcode:
    // library.proto
    export class OutStoreOrderReq {
        // 出库订单号
        OrderId:number = 0;

        // 出库图书参数
        BookParams:OutStoreParam[] = [];


    }
    // 出库
    /// Opcode:
    // library.proto
    export class OutStoreOrderRes {
        ErrCode:number = 0;


    }
    // 出库参数
    // com_library.proto
    export class OutStoreParam {
        // 图书id
        BookId:number = 0;

        // 图书数量
        Count:number = 0;


    }
    // com_passtime.proto
    export class PassTimeData {
        // 上次跨天时间
        LastPassDayTime:number = 0;


    }
    // com_player.proto
    export class PlayerData {
        account:string = "";

        playerId:number = 0;

        sex:number = 0;

        name:string = "";


    }
    /// Opcode:
    // player.proto
    export class PlayerDataNty {
        playerData:PlayerData = new PlayerData();


    }
    /// Opcode:
    // player.proto
    export class PlayerDataReq {
        account:string = "";

        pwd:string = "";


    }
    /// Opcode:
    // player.proto
    export class PlayerDataRes {
        errCode:number = 0;

        playerData:PlayerData = new PlayerData();

        loginToken:string = "";


    }
    // 退出: 必须把书还完
    /// Opcode:
    // library.proto
    export class QuitLibraryReq {

    }
    // 退出
    /// Opcode:
    // library.proto
    export class QuitLibraryRes {
        // 错误码
        ErrCode:number = 0;


    }
    // 阅读
    /// Opcode:
    // notify.proto
    export class ReadNotifyReq {
        NotifyId:number = 0;


    }
    // 阅读
    /// Opcode:
    // notify.proto
    export class ReadNotifyRes {
        ErrCode:number = 0;


    }
    // 注册节点信息
    /// Opcode:
    // heartbeat.proto
    export class RegisterNodeReq {
        NodeInfo:NodeHeartbeatInfo = new NodeHeartbeatInfo();


    }
    // 注册节点信息
    /// Opcode:
    // heartbeat.proto
    export class RegisterNodeRes {
        ErrCode:number = 0;


    }
    // com_user.proto
    export class RegisterUserInfo {
        // 账号
        AccountName:string = "";

        // 昵称
        Nickname:string = "";

        // 密码
        Pwd:string = "";

        // 创建的收集imei
        CreatePhoneImei:string = "";


    }
    // 移除通知数据
    /// Opcode:
    // notify.proto
    export class RemoveUserNotifyDataItemNty {
        // 要移除的通知id
        NotifyIds:number[] = [];


    }
    // 归还书
    /// Opcode:
    // library.proto
    export class ReturnBackReq {
        // 订单id
        OrderId:number = 0;

        // 指定自订单
        SubOrderIds:number[] = [];


    }
    // 归还书
    /// Opcode:
    // library.proto
    export class ReturnBackRes {
        ErrCode:number = 0;


    }
    // 按照权限大小排
    // com_library.proto
    export class RoleType {

    }
    // 改变书包数据
    /// Opcode:
    // bookbag.proto
    export class SetBookBagInfoReq {
        BookInfoItem:BookInfoItem = new BookInfoItem();


    }
    // 改变书包数据
    /// Opcode:
    // bookbag.proto
    export class SetBookBagInfoRes {
        ErrCode:number = 0;


    }
    // 表结构信息
    // com_system_table.proto
    export class SimpleInfo {
        // 当前自增id最大值（配合id池）
        MaxIncId:number = 0;

        // 标脏次数
        DirtyCount:number = 0;

        // 用于清档, 版本号和当前配置版本号不同则清档
        VersionNo:number = 0;


    }
    // 简要用户信息
    // com_user.proto
    export class SimpleUserInfo {
        // uid
        UserId:number = 0;

        // 昵称
        Nickname:string = "";

        // 绑定手机
        BindPhone:number = 0;


    }
    // 客户端显示用信息
    // com_book.proto
    export class SnapshotClientInfo {
        Id:number = 0;

        FilePath:string = "";


    }
    // 截图
    // com_library.proto
    export class SnapshotField {
        Snapshots:string[] = [];


    }
    // 借书
    /// Opcode:
    // bookbag.proto
    export class SubmitBookBagBorrowInfoReq {
        // 备注
        Remark:string = "";


    }
    // 借书
    /// Opcode:
    // bookbag.proto
    export class SubmitBookBagBorrowInfoRes {
        ErrCode:number = 0;


    }
    // com_syslog.proto
    export class SystemLogData {
        Id:number = 0;

        libraryId:number = 0;

        // title文字id
        TitleWordId:string = "";

        // title的参数
        TitleParams:VariantParam[] = [];

        // 内容文字id
        ContentWordId:string = "";

        // 内容的参数
        ContentParams:VariantParam[] = [];

        // 时间
        CreateTime:number = 0;


    }
    // 系统日志
    /// Opcode:
    // syslog.proto
    export class SystemLogDataListReq {
        BaseLogId:number = 0;

        // 数量 负数表示 BaseNotifyId 之前的前n个日志, 正数表示 BaseNotifyId 之后n个日志
        Count:number = 0;


    }
    // 系统日志
    /// Opcode:
    // syslog.proto
    export class SystemLogDataListRes {
        LogList:SystemLogData[] = [];

        // 负数表示往前n个日志, 正数表示末尾n个日志
        Count:number = 0;


    }
    // com_user.proto
    export class TestCustomData {
        TestInt:number = 0;


    }
    // comp_test.proto
    export class TestMgrData {
        Account:string = "";

        TestId:number = 0;


    }
    /// Opcode:
    // test_opcode.proto
    export class TestOpcode2Req {
        id:number = 0;

        content:string = "";


    }
    /// Opcode:
    // test_opcode.proto
    export class TestOpcode2Res {
        id_info:number = 0;

        testInfo:TestOpcodeInfo = new TestOpcodeInfo();


    }
    // test_opcode.proto
    export class TestOpcodeInfo {
        errCode:number = 0;

        errMsg:string = "";


    }
    // bytes 数据结构转json的时候会转成base64编码
    /// Opcode:
    // test_opcode.proto
    export class TestOpcodeReq {
        content:string = "";

        TestId:number = 0;


    }
    /// Opcode:
    // test_opcode.proto
    export class TestOpcodeRes {
        content:string = "";

        TestId:number = 0;


    }
    /// EnableStorage:true
    // com_user.proto
    export class TestOrm {
        TestInt:number = 0;

        TestString:string = "";

        TestIntArray:number[] = [];

        TestStringArray:string[] = [];

        TestCustom:TestCustomData = new TestCustomData();

        TestCustomArray:TestCustomData[] = [];

        TestOneOfInt?:number;

        TestOneOfString?:string;

        TestOneOfCustom?:TestCustomData;


    }
    // com_title.proto
    export class TitleInfo {
        titleCfgId:number = 0;

        expiredTs:number = 0;


    }
    /// Opcode:
    // title.proto
    export class TitleInfoReq {

    }
    /// Opcode:
    // title.proto
    export class TitleInfoRes {
        errCode:number = 0;

        titleList:TitleInfo[] = [];


    }
    // 转让馆长:只能转让给管理员, 转让后降级成管理员 TODO:
    /// Opcode:
    // library.proto
    export class TransferLibraianReq {
        TargetUserId:number = 0;


    }
    // 转让馆长
    /// Opcode:
    // library.proto
    export class TransferLibraianRes {
        ErrCode:number = 0;


    }
    /// EnableStorage:true
    // com_user.proto
    export class UserBaseInfo {
        // uid
        UserId:number = 0;

        // 账号
        AccountName:string = "";

        // 姓名
        Name:string = "";

        // 昵称
        Nickname:string = "";

        // 密码
        Pwd:string = "";

        // 盐
        PwdSalt:string = "";

        // 绑定手机
        BindPhone:number = 0;

        // 最后登录时间
        LastLoginTime:number = 0;

        // 最后登录ip
        LastLoginIp:string = "";

        // 最后登录收集imei
        LastLoginPhoneImei:string = "";

        // 创建号的ip
        CreateIp:string = "";

        // 创建时间
        CreateTime:number = 0;

        // 创建的收集imei
        CreatePhoneImei:string = "";

        // 绑定的邮箱地址
        BindMailAddr:string = "";

        // 上次跨天时间
        LastPassDayTime:number = 0;


    }
    /// Opcode:
    // user.proto
    export class UserClientInfoNty {
        ClientInfo:ClientUserInfo = new ClientUserInfo();


    }
    // 确认领取推送确认码(确认码有效期2分钟)
    /// Opcode:
    // library.proto
    export class UserGetBooksOrderConfirmNty {
        OrderId:number = 0;

        ConfirmCode:number = 0;


    }
    // 用户领书确认
    /// Opcode:
    // library.proto
    export class UserGetBooksOrderConfirmReq {
        OrderId:number = 0;

        ConfirmCode:number = 0;


    }
    // 用户领书确认
    /// Opcode:
    // library.proto
    export class UserGetBooksOrderConfirmRes {
        ErrCode:number = 0;


    }
    // 玩家的图书馆数据
    // com_library.proto
    export class UserLibraryInfo {
        // 图书馆id
        LibraryId:number = 0;


    }
    // 用户的图书馆简要信息
    /// Opcode:
    // library.proto
    export class UserLibraryInfoNty {
        UserLibraryInfo:UserLibraryInfo = new UserLibraryInfo();


    }
    // com_login.proto
    export class UserLoginInfo {
        // 生成的token = sha1(imei + ip + userid + key)
        Token:string = "";

        // 生成的随机密钥(8位随机数或字符)
        Key:string = "";

        // 密钥过期时间 精确到秒
        KeyExpireTime:number = 0;


    }
    // 数据变更通知
    /// Opcode:
    // notify.proto
    export class UserNotifyChangeNty {
        ItemList:UserNotifyDataItem[] = [];


    }
    // com_notify.proto
    export class UserNotifyData {
        ItemList:UserNotifyDataItem[] = [];


    }
    // 通知数据
    // com_notify.proto
    export class UserNotifyDataItem {
        // 用于识别的唯一id
        NotifyId:number = 0;

        // 通知的title文字id
        NotifyTitleWordId:string = "";

        // title的参数
        TitleParams:VariantParam[] = [];

        // 通知的内容文字id
        NotifyContentWordId:string = "";

        // 内容的参数
        ContentParams:VariantParam[] = [];

        // 时间
        CreateTime:number = 0;

        // 是否已读
        IsRead:number = 0;


    }
    // 通知数据
    /// Opcode:
    // notify.proto
    export class UserNotifyDataNty {
        UserNotifyData:UserNotifyData = new UserNotifyData();


    }
    // com_variant.proto
    export class VariantParam {
        // 参数类型
        VariantType:number = 0;

        // 字符串
        StrValue?:string;

        // 整数类型
        IntValue?:number;

        // 无符号整数类型
        UnSignedValue?:number;

        // 浮点数
        DoubleValue?:number;


    }
    // com_variant.proto
    export class VariantParamType {

    }

}