/*!
*  MIT License
*  
*  Copyright (c) 2020 ericyonng<120453674@qq.com>
*  
*  Permission is hereby granted, free of charge, to any person obtaining a copy
*  of this software and associated documentation files (the "Software"), to deal
*  in the Software without restriction, including without limitation the rights
*  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*  copies of the Software, and to permit persons to whom the Software is
*  furnished to do so, subject to the following conditions:
*  
*  The above copyright notice and this permission notice shall be included in all
*  copies or substantial portions of the Software.
*  
*  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
*  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
*  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
*  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
*  SOFTWARE.
* 
* Author: Eric Yonng
* Description: Generated By protogentool, Dont Modify This File!!!
*/


export namespace ts_pbinfo{

    // login.proto 
    export class LoginReq {
      getOpcode():number {return LoginReq.OPCODE; }
      getIsXorEncrypt():boolean {return LoginReq.XorEncrypt; }
      getIsKeyBase64():boolean {return LoginReq.KeyBase64; }
      getOpcodeName():string {return LoginReq.OPCODE_NAME; }
      static OPCODE:number = 1;
      static OPCODE_NAME:string = "LoginReq";
      static XorEncrypt:boolean = true;
      static KeyBase64:boolean = true;
    }


    // login.proto 
    export class LoginRes {
      getOpcode():number {return LoginRes.OPCODE; }
      getIsXorEncrypt():boolean {return LoginRes.XorEncrypt; }
      getIsKeyBase64():boolean {return LoginRes.KeyBase64; }
      getOpcodeName():string {return LoginRes.OPCODE_NAME; }
      static OPCODE:number = 2;
      static OPCODE_NAME:string = "LoginRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // test_opcode.proto 
    export class TestOpcodeReq {
      getOpcode():number {return TestOpcodeReq.OPCODE; }
      getIsXorEncrypt():boolean {return TestOpcodeReq.XorEncrypt; }
      getIsKeyBase64():boolean {return TestOpcodeReq.KeyBase64; }
      getOpcodeName():string {return TestOpcodeReq.OPCODE_NAME; }
      static OPCODE:number = 3;
      static OPCODE_NAME:string = "TestOpcodeReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // test_opcode.proto 
    export class TestOpcodeRes {
      getOpcode():number {return TestOpcodeRes.OPCODE; }
      getIsXorEncrypt():boolean {return TestOpcodeRes.XorEncrypt; }
      getIsKeyBase64():boolean {return TestOpcodeRes.KeyBase64; }
      getOpcodeName():string {return TestOpcodeRes.OPCODE_NAME; }
      static OPCODE:number = 4;
      static OPCODE_NAME:string = "TestOpcodeRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // test_opcode.proto 
    export class TestOpcode2Req {
      getOpcode():number {return TestOpcode2Req.OPCODE; }
      getIsXorEncrypt():boolean {return TestOpcode2Req.XorEncrypt; }
      getIsKeyBase64():boolean {return TestOpcode2Req.KeyBase64; }
      getOpcodeName():string {return TestOpcode2Req.OPCODE_NAME; }
      static OPCODE:number = 5;
      static OPCODE_NAME:string = "TestOpcode2Req";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // test_opcode.proto 
    export class TestOpcode2Res {
      getOpcode():number {return TestOpcode2Res.OPCODE; }
      getIsXorEncrypt():boolean {return TestOpcode2Res.XorEncrypt; }
      getIsKeyBase64():boolean {return TestOpcode2Res.KeyBase64; }
      getOpcodeName():string {return TestOpcode2Res.OPCODE_NAME; }
      static OPCODE:number = 6;
      static OPCODE_NAME:string = "TestOpcode2Res";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // player.proto 
    export class PlayerDataReq {
      getOpcode():number {return PlayerDataReq.OPCODE; }
      getIsXorEncrypt():boolean {return PlayerDataReq.XorEncrypt; }
      getIsKeyBase64():boolean {return PlayerDataReq.KeyBase64; }
      getOpcodeName():string {return PlayerDataReq.OPCODE_NAME; }
      static OPCODE:number = 7;
      static OPCODE_NAME:string = "PlayerDataReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // player.proto 
    export class PlayerDataRes {
      getOpcode():number {return PlayerDataRes.OPCODE; }
      getIsXorEncrypt():boolean {return PlayerDataRes.XorEncrypt; }
      getIsKeyBase64():boolean {return PlayerDataRes.KeyBase64; }
      getOpcodeName():string {return PlayerDataRes.OPCODE_NAME; }
      static OPCODE:number = 8;
      static OPCODE_NAME:string = "PlayerDataRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // player.proto 
    export class ModifyPlayerNameReq {
      getOpcode():number {return ModifyPlayerNameReq.OPCODE; }
      getIsXorEncrypt():boolean {return ModifyPlayerNameReq.XorEncrypt; }
      getIsKeyBase64():boolean {return ModifyPlayerNameReq.KeyBase64; }
      getOpcodeName():string {return ModifyPlayerNameReq.OPCODE_NAME; }
      static OPCODE:number = 9;
      static OPCODE_NAME:string = "ModifyPlayerNameReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // player.proto 
    export class ModifyPlayerNameRes {
      getOpcode():number {return ModifyPlayerNameRes.OPCODE; }
      getIsXorEncrypt():boolean {return ModifyPlayerNameRes.XorEncrypt; }
      getIsKeyBase64():boolean {return ModifyPlayerNameRes.KeyBase64; }
      getOpcodeName():string {return ModifyPlayerNameRes.OPCODE_NAME; }
      static OPCODE:number = 10;
      static OPCODE_NAME:string = "ModifyPlayerNameRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // player.proto 
    export class PlayerDataNty {
      getOpcode():number {return PlayerDataNty.OPCODE; }
      getIsXorEncrypt():boolean {return PlayerDataNty.XorEncrypt; }
      getIsKeyBase64():boolean {return PlayerDataNty.KeyBase64; }
      getOpcodeName():string {return PlayerDataNty.OPCODE_NAME; }
      static OPCODE:number = 11;
      static OPCODE_NAME:string = "PlayerDataNty";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // title.proto 
    export class TitleInfoReq {
      getOpcode():number {return TitleInfoReq.OPCODE; }
      getIsXorEncrypt():boolean {return TitleInfoReq.XorEncrypt; }
      getIsKeyBase64():boolean {return TitleInfoReq.KeyBase64; }
      getOpcodeName():string {return TitleInfoReq.OPCODE_NAME; }
      static OPCODE:number = 20;
      static OPCODE_NAME:string = "TitleInfoReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // title.proto 
    export class TitleInfoRes {
      getOpcode():number {return TitleInfoRes.OPCODE; }
      getIsXorEncrypt():boolean {return TitleInfoRes.XorEncrypt; }
      getIsKeyBase64():boolean {return TitleInfoRes.KeyBase64; }
      getOpcodeName():string {return TitleInfoRes.OPCODE_NAME; }
      static OPCODE:number = 21;
      static OPCODE_NAME:string = "TitleInfoRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // login.proto 
    export class LoginInfoNty {
      getOpcode():number {return LoginInfoNty.OPCODE; }
      getIsXorEncrypt():boolean {return LoginInfoNty.XorEncrypt; }
      getIsKeyBase64():boolean {return LoginInfoNty.KeyBase64; }
      getOpcodeName():string {return LoginInfoNty.OPCODE_NAME; }
      static OPCODE:number = 22;
      static OPCODE_NAME:string = "LoginInfoNty";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // heartbeat.proto 
    export class NodeHeartbeatReq {
      getOpcode():number {return NodeHeartbeatReq.OPCODE; }
      getIsXorEncrypt():boolean {return NodeHeartbeatReq.XorEncrypt; }
      getIsKeyBase64():boolean {return NodeHeartbeatReq.KeyBase64; }
      getOpcodeName():string {return NodeHeartbeatReq.OPCODE_NAME; }
      static OPCODE:number = 23;
      static OPCODE_NAME:string = "NodeHeartbeatReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // heartbeat.proto 
    export class NodeHeartbeatRes {
      getOpcode():number {return NodeHeartbeatRes.OPCODE; }
      getIsXorEncrypt():boolean {return NodeHeartbeatRes.XorEncrypt; }
      getIsKeyBase64():boolean {return NodeHeartbeatRes.KeyBase64; }
      getOpcodeName():string {return NodeHeartbeatRes.OPCODE_NAME; }
      static OPCODE:number = 24;
      static OPCODE_NAME:string = "NodeHeartbeatRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // heartbeat.proto 
    export class RegisterNodeReq {
      getOpcode():number {return RegisterNodeReq.OPCODE; }
      getIsXorEncrypt():boolean {return RegisterNodeReq.XorEncrypt; }
      getIsKeyBase64():boolean {return RegisterNodeReq.KeyBase64; }
      getOpcodeName():string {return RegisterNodeReq.OPCODE_NAME; }
      static OPCODE:number = 25;
      static OPCODE_NAME:string = "RegisterNodeReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // heartbeat.proto 
    export class RegisterNodeRes {
      getOpcode():number {return RegisterNodeRes.OPCODE; }
      getIsXorEncrypt():boolean {return RegisterNodeRes.XorEncrypt; }
      getIsKeyBase64():boolean {return RegisterNodeRes.KeyBase64; }
      getOpcodeName():string {return RegisterNodeRes.OPCODE_NAME; }
      static OPCODE:number = 26;
      static OPCODE_NAME:string = "RegisterNodeRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // heartbeat.proto 
    export class GetNodeListReq {
      getOpcode():number {return GetNodeListReq.OPCODE; }
      getIsXorEncrypt():boolean {return GetNodeListReq.XorEncrypt; }
      getIsKeyBase64():boolean {return GetNodeListReq.KeyBase64; }
      getOpcodeName():string {return GetNodeListReq.OPCODE_NAME; }
      static OPCODE:number = 27;
      static OPCODE_NAME:string = "GetNodeListReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // heartbeat.proto 
    export class GetNodeListRes {
      getOpcode():number {return GetNodeListRes.OPCODE; }
      getIsXorEncrypt():boolean {return GetNodeListRes.XorEncrypt; }
      getIsKeyBase64():boolean {return GetNodeListRes.KeyBase64; }
      getOpcodeName():string {return GetNodeListRes.OPCODE_NAME; }
      static OPCODE:number = 28;
      static OPCODE_NAME:string = "GetNodeListRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // heartbeat.proto 
    export class ClientHeartbeatReq {
      getOpcode():number {return ClientHeartbeatReq.OPCODE; }
      getIsXorEncrypt():boolean {return ClientHeartbeatReq.XorEncrypt; }
      getIsKeyBase64():boolean {return ClientHeartbeatReq.KeyBase64; }
      getOpcodeName():string {return ClientHeartbeatReq.OPCODE_NAME; }
      static OPCODE:number = 29;
      static OPCODE_NAME:string = "ClientHeartbeatReq";
      static XorEncrypt:boolean = true;
      static KeyBase64:boolean = true;
    }


    // heartbeat.proto 
    export class ClientHeartbeatRes {
      getOpcode():number {return ClientHeartbeatRes.OPCODE; }
      getIsXorEncrypt():boolean {return ClientHeartbeatRes.XorEncrypt; }
      getIsKeyBase64():boolean {return ClientHeartbeatRes.KeyBase64; }
      getOpcodeName():string {return ClientHeartbeatRes.OPCODE_NAME; }
      static OPCODE:number = 30;
      static OPCODE_NAME:string = "ClientHeartbeatRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // login.proto 
    export class LogoutReq {
      getOpcode():number {return LogoutReq.OPCODE; }
      getIsXorEncrypt():boolean {return LogoutReq.XorEncrypt; }
      getIsKeyBase64():boolean {return LogoutReq.KeyBase64; }
      getOpcodeName():string {return LogoutReq.OPCODE_NAME; }
      static OPCODE:number = 31;
      static OPCODE_NAME:string = "LogoutReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // login.proto 
    export class LogoutNty {
      getOpcode():number {return LogoutNty.OPCODE; }
      getIsXorEncrypt():boolean {return LogoutNty.XorEncrypt; }
      getIsKeyBase64():boolean {return LogoutNty.KeyBase64; }
      getOpcodeName():string {return LogoutNty.OPCODE_NAME; }
      static OPCODE:number = 32;
      static OPCODE_NAME:string = "LogoutNty";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // user.proto 
    export class UserClientInfoNty {
      getOpcode():number {return UserClientInfoNty.OPCODE; }
      getIsXorEncrypt():boolean {return UserClientInfoNty.XorEncrypt; }
      getIsKeyBase64():boolean {return UserClientInfoNty.KeyBase64; }
      getOpcodeName():string {return UserClientInfoNty.OPCODE_NAME; }
      static OPCODE:number = 37;
      static OPCODE_NAME:string = "UserClientInfoNty";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class GetLibraryInfoReq {
      getOpcode():number {return GetLibraryInfoReq.OPCODE; }
      getIsXorEncrypt():boolean {return GetLibraryInfoReq.XorEncrypt; }
      getIsKeyBase64():boolean {return GetLibraryInfoReq.KeyBase64; }
      getOpcodeName():string {return GetLibraryInfoReq.OPCODE_NAME; }
      static OPCODE:number = 42;
      static OPCODE_NAME:string = "GetLibraryInfoReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class GetLibraryInfoRes {
      getOpcode():number {return GetLibraryInfoRes.OPCODE; }
      getIsXorEncrypt():boolean {return GetLibraryInfoRes.XorEncrypt; }
      getIsKeyBase64():boolean {return GetLibraryInfoRes.KeyBase64; }
      getOpcodeName():string {return GetLibraryInfoRes.OPCODE_NAME; }
      static OPCODE:number = 43;
      static OPCODE_NAME:string = "GetLibraryInfoRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class CreateLibraryReq {
      getOpcode():number {return CreateLibraryReq.OPCODE; }
      getIsXorEncrypt():boolean {return CreateLibraryReq.XorEncrypt; }
      getIsKeyBase64():boolean {return CreateLibraryReq.KeyBase64; }
      getOpcodeName():string {return CreateLibraryReq.OPCODE_NAME; }
      static OPCODE:number = 44;
      static OPCODE_NAME:string = "CreateLibraryReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class CreateLibraryRes {
      getOpcode():number {return CreateLibraryRes.OPCODE; }
      getIsXorEncrypt():boolean {return CreateLibraryRes.XorEncrypt; }
      getIsKeyBase64():boolean {return CreateLibraryRes.KeyBase64; }
      getOpcodeName():string {return CreateLibraryRes.OPCODE_NAME; }
      static OPCODE:number = 45;
      static OPCODE_NAME:string = "CreateLibraryRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class LibraryInfoNty {
      getOpcode():number {return LibraryInfoNty.OPCODE; }
      getIsXorEncrypt():boolean {return LibraryInfoNty.XorEncrypt; }
      getIsKeyBase64():boolean {return LibraryInfoNty.KeyBase64; }
      getOpcodeName():string {return LibraryInfoNty.OPCODE_NAME; }
      static OPCODE:number = 46;
      static OPCODE_NAME:string = "LibraryInfoNty";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class JoinLibraryReq {
      getOpcode():number {return JoinLibraryReq.OPCODE; }
      getIsXorEncrypt():boolean {return JoinLibraryReq.XorEncrypt; }
      getIsKeyBase64():boolean {return JoinLibraryReq.KeyBase64; }
      getOpcodeName():string {return JoinLibraryReq.OPCODE_NAME; }
      static OPCODE:number = 47;
      static OPCODE_NAME:string = "JoinLibraryReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class JoinLibraryRes {
      getOpcode():number {return JoinLibraryRes.OPCODE; }
      getIsXorEncrypt():boolean {return JoinLibraryRes.XorEncrypt; }
      getIsKeyBase64():boolean {return JoinLibraryRes.KeyBase64; }
      getOpcodeName():string {return JoinLibraryRes.OPCODE_NAME; }
      static OPCODE:number = 48;
      static OPCODE_NAME:string = "JoinLibraryRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class GetLibraryListReq {
      getOpcode():number {return GetLibraryListReq.OPCODE; }
      getIsXorEncrypt():boolean {return GetLibraryListReq.XorEncrypt; }
      getIsKeyBase64():boolean {return GetLibraryListReq.KeyBase64; }
      getOpcodeName():string {return GetLibraryListReq.OPCODE_NAME; }
      static OPCODE:number = 49;
      static OPCODE_NAME:string = "GetLibraryListReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class GetLibraryListRes {
      getOpcode():number {return GetLibraryListRes.OPCODE; }
      getIsXorEncrypt():boolean {return GetLibraryListRes.XorEncrypt; }
      getIsKeyBase64():boolean {return GetLibraryListRes.KeyBase64; }
      getOpcodeName():string {return GetLibraryListRes.OPCODE_NAME; }
      static OPCODE:number = 50;
      static OPCODE_NAME:string = "GetLibraryListRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class QuitLibraryReq {
      getOpcode():number {return QuitLibraryReq.OPCODE; }
      getIsXorEncrypt():boolean {return QuitLibraryReq.XorEncrypt; }
      getIsKeyBase64():boolean {return QuitLibraryReq.KeyBase64; }
      getOpcodeName():string {return QuitLibraryReq.OPCODE_NAME; }
      static OPCODE:number = 51;
      static OPCODE_NAME:string = "QuitLibraryReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class QuitLibraryRes {
      getOpcode():number {return QuitLibraryRes.OPCODE; }
      getIsXorEncrypt():boolean {return QuitLibraryRes.XorEncrypt; }
      getIsKeyBase64():boolean {return QuitLibraryRes.KeyBase64; }
      getOpcodeName():string {return QuitLibraryRes.OPCODE_NAME; }
      static OPCODE:number = 52;
      static OPCODE_NAME:string = "QuitLibraryRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class TransferLibraianReq {
      getOpcode():number {return TransferLibraianReq.OPCODE; }
      getIsXorEncrypt():boolean {return TransferLibraianReq.XorEncrypt; }
      getIsKeyBase64():boolean {return TransferLibraianReq.KeyBase64; }
      getOpcodeName():string {return TransferLibraianReq.OPCODE_NAME; }
      static OPCODE:number = 53;
      static OPCODE_NAME:string = "TransferLibraianReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class TransferLibraianRes {
      getOpcode():number {return TransferLibraianRes.OPCODE; }
      getIsXorEncrypt():boolean {return TransferLibraianRes.XorEncrypt; }
      getIsKeyBase64():boolean {return TransferLibraianRes.KeyBase64; }
      getOpcodeName():string {return TransferLibraianRes.OPCODE_NAME; }
      static OPCODE:number = 54;
      static OPCODE_NAME:string = "TransferLibraianRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class ModifyMemberInfoReq {
      getOpcode():number {return ModifyMemberInfoReq.OPCODE; }
      getIsXorEncrypt():boolean {return ModifyMemberInfoReq.XorEncrypt; }
      getIsKeyBase64():boolean {return ModifyMemberInfoReq.KeyBase64; }
      getOpcodeName():string {return ModifyMemberInfoReq.OPCODE_NAME; }
      static OPCODE:number = 55;
      static OPCODE_NAME:string = "ModifyMemberInfoReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class ModifyMemberInfoRes {
      getOpcode():number {return ModifyMemberInfoRes.OPCODE; }
      getIsXorEncrypt():boolean {return ModifyMemberInfoRes.XorEncrypt; }
      getIsKeyBase64():boolean {return ModifyMemberInfoRes.KeyBase64; }
      getOpcodeName():string {return ModifyMemberInfoRes.OPCODE_NAME; }
      static OPCODE:number = 56;
      static OPCODE_NAME:string = "ModifyMemberInfoRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class UserLibraryInfoNty {
      getOpcode():number {return UserLibraryInfoNty.OPCODE; }
      getIsXorEncrypt():boolean {return UserLibraryInfoNty.XorEncrypt; }
      getIsKeyBase64():boolean {return UserLibraryInfoNty.KeyBase64; }
      getOpcodeName():string {return UserLibraryInfoNty.OPCODE_NAME; }
      static OPCODE:number = 57;
      static OPCODE_NAME:string = "UserLibraryInfoNty";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // user.proto 
    export class ModifyUserInfoReq {
      getOpcode():number {return ModifyUserInfoReq.OPCODE; }
      getIsXorEncrypt():boolean {return ModifyUserInfoReq.XorEncrypt; }
      getIsKeyBase64():boolean {return ModifyUserInfoReq.KeyBase64; }
      getOpcodeName():string {return ModifyUserInfoReq.OPCODE_NAME; }
      static OPCODE:number = 58;
      static OPCODE_NAME:string = "ModifyUserInfoReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // user.proto 
    export class ModifyUserInfoRes {
      getOpcode():number {return ModifyUserInfoRes.OPCODE; }
      getIsXorEncrypt():boolean {return ModifyUserInfoRes.XorEncrypt; }
      getIsKeyBase64():boolean {return ModifyUserInfoRes.KeyBase64; }
      getOpcodeName():string {return ModifyUserInfoRes.OPCODE_NAME; }
      static OPCODE:number = 59;
      static OPCODE_NAME:string = "ModifyUserInfoRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // login.proto 
    export class LoginFinishReq {
      getOpcode():number {return LoginFinishReq.OPCODE; }
      getIsXorEncrypt():boolean {return LoginFinishReq.XorEncrypt; }
      getIsKeyBase64():boolean {return LoginFinishReq.KeyBase64; }
      getOpcodeName():string {return LoginFinishReq.OPCODE_NAME; }
      static OPCODE:number = 60;
      static OPCODE_NAME:string = "LoginFinishReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // login.proto 
    export class LoginFinishRes {
      getOpcode():number {return LoginFinishRes.OPCODE; }
      getIsXorEncrypt():boolean {return LoginFinishRes.XorEncrypt; }
      getIsKeyBase64():boolean {return LoginFinishRes.KeyBase64; }
      getOpcodeName():string {return LoginFinishRes.OPCODE_NAME; }
      static OPCODE:number = 61;
      static OPCODE_NAME:string = "LoginFinishRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class GetLibraryMemberSimpleInfoReq {
      getOpcode():number {return GetLibraryMemberSimpleInfoReq.OPCODE; }
      getIsXorEncrypt():boolean {return GetLibraryMemberSimpleInfoReq.XorEncrypt; }
      getIsKeyBase64():boolean {return GetLibraryMemberSimpleInfoReq.KeyBase64; }
      getOpcodeName():string {return GetLibraryMemberSimpleInfoReq.OPCODE_NAME; }
      static OPCODE:number = 62;
      static OPCODE_NAME:string = "GetLibraryMemberSimpleInfoReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class GetLibraryMemberSimpleInfoRes {
      getOpcode():number {return GetLibraryMemberSimpleInfoRes.OPCODE; }
      getIsXorEncrypt():boolean {return GetLibraryMemberSimpleInfoRes.XorEncrypt; }
      getIsKeyBase64():boolean {return GetLibraryMemberSimpleInfoRes.KeyBase64; }
      getOpcodeName():string {return GetLibraryMemberSimpleInfoRes.OPCODE_NAME; }
      static OPCODE:number = 63;
      static OPCODE_NAME:string = "GetLibraryMemberSimpleInfoRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class AddLibraryBookReq {
      getOpcode():number {return AddLibraryBookReq.OPCODE; }
      getIsXorEncrypt():boolean {return AddLibraryBookReq.XorEncrypt; }
      getIsKeyBase64():boolean {return AddLibraryBookReq.KeyBase64; }
      getOpcodeName():string {return AddLibraryBookReq.OPCODE_NAME; }
      static OPCODE:number = 64;
      static OPCODE_NAME:string = "AddLibraryBookReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class AddLibraryBookRes {
      getOpcode():number {return AddLibraryBookRes.OPCODE; }
      getIsXorEncrypt():boolean {return AddLibraryBookRes.XorEncrypt; }
      getIsKeyBase64():boolean {return AddLibraryBookRes.KeyBase64; }
      getOpcodeName():string {return AddLibraryBookRes.OPCODE_NAME; }
      static OPCODE:number = 65;
      static OPCODE_NAME:string = "AddLibraryBookRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class AddLibraryBookCountReq {
      getOpcode():number {return AddLibraryBookCountReq.OPCODE; }
      getIsXorEncrypt():boolean {return AddLibraryBookCountReq.XorEncrypt; }
      getIsKeyBase64():boolean {return AddLibraryBookCountReq.KeyBase64; }
      getOpcodeName():string {return AddLibraryBookCountReq.OPCODE_NAME; }
      static OPCODE:number = 66;
      static OPCODE_NAME:string = "AddLibraryBookCountReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class AddLibraryBookCountRes {
      getOpcode():number {return AddLibraryBookCountRes.OPCODE; }
      getIsXorEncrypt():boolean {return AddLibraryBookCountRes.XorEncrypt; }
      getIsKeyBase64():boolean {return AddLibraryBookCountRes.KeyBase64; }
      getOpcodeName():string {return AddLibraryBookCountRes.OPCODE_NAME; }
      static OPCODE:number = 67;
      static OPCODE_NAME:string = "AddLibraryBookCountRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class GetBookListReq {
      getOpcode():number {return GetBookListReq.OPCODE; }
      getIsXorEncrypt():boolean {return GetBookListReq.XorEncrypt; }
      getIsKeyBase64():boolean {return GetBookListReq.KeyBase64; }
      getOpcodeName():string {return GetBookListReq.OPCODE_NAME; }
      static OPCODE:number = 68;
      static OPCODE_NAME:string = "GetBookListReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class BookListNty {
      getOpcode():number {return BookListNty.OPCODE; }
      getIsXorEncrypt():boolean {return BookListNty.XorEncrypt; }
      getIsKeyBase64():boolean {return BookListNty.KeyBase64; }
      getOpcodeName():string {return BookListNty.OPCODE_NAME; }
      static OPCODE:number = 69;
      static OPCODE_NAME:string = "BookListNty";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class BooksChangeNty {
      getOpcode():number {return BooksChangeNty.OPCODE; }
      getIsXorEncrypt():boolean {return BooksChangeNty.XorEncrypt; }
      getIsKeyBase64():boolean {return BooksChangeNty.KeyBase64; }
      getOpcodeName():string {return BooksChangeNty.OPCODE_NAME; }
      static OPCODE:number = 70;
      static OPCODE_NAME:string = "BooksChangeNty";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class GetBookListRes {
      getOpcode():number {return GetBookListRes.OPCODE; }
      getIsXorEncrypt():boolean {return GetBookListRes.XorEncrypt; }
      getIsKeyBase64():boolean {return GetBookListRes.KeyBase64; }
      getOpcodeName():string {return GetBookListRes.OPCODE_NAME; }
      static OPCODE:number = 72;
      static OPCODE_NAME:string = "GetBookListRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class BookVariantInfoItemsNty {
      getOpcode():number {return BookVariantInfoItemsNty.OPCODE; }
      getIsXorEncrypt():boolean {return BookVariantInfoItemsNty.XorEncrypt; }
      getIsKeyBase64():boolean {return BookVariantInfoItemsNty.KeyBase64; }
      getOpcodeName():string {return BookVariantInfoItemsNty.OPCODE_NAME; }
      static OPCODE:number = 73;
      static OPCODE_NAME:string = "BookVariantInfoItemsNty";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class GetBookInfoReq {
      getOpcode():number {return GetBookInfoReq.OPCODE; }
      getIsXorEncrypt():boolean {return GetBookInfoReq.XorEncrypt; }
      getIsKeyBase64():boolean {return GetBookInfoReq.KeyBase64; }
      getOpcodeName():string {return GetBookInfoReq.OPCODE_NAME; }
      static OPCODE:number = 74;
      static OPCODE_NAME:string = "GetBookInfoReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class GetBookInfoRes {
      getOpcode():number {return GetBookInfoRes.OPCODE; }
      getIsXorEncrypt():boolean {return GetBookInfoRes.XorEncrypt; }
      getIsKeyBase64():boolean {return GetBookInfoRes.KeyBase64; }
      getOpcodeName():string {return GetBookInfoRes.OPCODE_NAME; }
      static OPCODE:number = 75;
      static OPCODE_NAME:string = "GetBookInfoRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class GetBookByBookNameReq {
      getOpcode():number {return GetBookByBookNameReq.OPCODE; }
      getIsXorEncrypt():boolean {return GetBookByBookNameReq.XorEncrypt; }
      getIsKeyBase64():boolean {return GetBookByBookNameReq.KeyBase64; }
      getOpcodeName():string {return GetBookByBookNameReq.OPCODE_NAME; }
      static OPCODE:number = 76;
      static OPCODE_NAME:string = "GetBookByBookNameReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class GetBookByBookNameRes {
      getOpcode():number {return GetBookByBookNameRes.OPCODE; }
      getIsXorEncrypt():boolean {return GetBookByBookNameRes.XorEncrypt; }
      getIsKeyBase64():boolean {return GetBookByBookNameRes.KeyBase64; }
      getOpcodeName():string {return GetBookByBookNameRes.OPCODE_NAME; }
      static OPCODE:number = 77;
      static OPCODE_NAME:string = "GetBookByBookNameRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // bookbag.proto 
    export class BookBagInfoReq {
      getOpcode():number {return BookBagInfoReq.OPCODE; }
      getIsXorEncrypt():boolean {return BookBagInfoReq.XorEncrypt; }
      getIsKeyBase64():boolean {return BookBagInfoReq.KeyBase64; }
      getOpcodeName():string {return BookBagInfoReq.OPCODE_NAME; }
      static OPCODE:number = 80;
      static OPCODE_NAME:string = "BookBagInfoReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // bookbag.proto 
    export class BookBagInfoNty {
      getOpcode():number {return BookBagInfoNty.OPCODE; }
      getIsXorEncrypt():boolean {return BookBagInfoNty.XorEncrypt; }
      getIsKeyBase64():boolean {return BookBagInfoNty.KeyBase64; }
      getOpcodeName():string {return BookBagInfoNty.OPCODE_NAME; }
      static OPCODE:number = 81;
      static OPCODE_NAME:string = "BookBagInfoNty";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // bookbag.proto 
    export class BookBagInfoRes {
      getOpcode():number {return BookBagInfoRes.OPCODE; }
      getIsXorEncrypt():boolean {return BookBagInfoRes.XorEncrypt; }
      getIsKeyBase64():boolean {return BookBagInfoRes.KeyBase64; }
      getOpcodeName():string {return BookBagInfoRes.OPCODE_NAME; }
      static OPCODE:number = 82;
      static OPCODE_NAME:string = "BookBagInfoRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // bookbag.proto 
    export class SetBookBagInfoReq {
      getOpcode():number {return SetBookBagInfoReq.OPCODE; }
      getIsXorEncrypt():boolean {return SetBookBagInfoReq.XorEncrypt; }
      getIsKeyBase64():boolean {return SetBookBagInfoReq.KeyBase64; }
      getOpcodeName():string {return SetBookBagInfoReq.OPCODE_NAME; }
      static OPCODE:number = 83;
      static OPCODE_NAME:string = "SetBookBagInfoReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // bookbag.proto 
    export class SetBookBagInfoRes {
      getOpcode():number {return SetBookBagInfoRes.OPCODE; }
      getIsXorEncrypt():boolean {return SetBookBagInfoRes.XorEncrypt; }
      getIsKeyBase64():boolean {return SetBookBagInfoRes.KeyBase64; }
      getOpcodeName():string {return SetBookBagInfoRes.OPCODE_NAME; }
      static OPCODE:number = 84;
      static OPCODE_NAME:string = "SetBookBagInfoRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class GetBookInfoListReq {
      getOpcode():number {return GetBookInfoListReq.OPCODE; }
      getIsXorEncrypt():boolean {return GetBookInfoListReq.XorEncrypt; }
      getIsKeyBase64():boolean {return GetBookInfoListReq.KeyBase64; }
      getOpcodeName():string {return GetBookInfoListReq.OPCODE_NAME; }
      static OPCODE:number = 85;
      static OPCODE_NAME:string = "GetBookInfoListReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class GetBookInfoListRes {
      getOpcode():number {return GetBookInfoListRes.OPCODE; }
      getIsXorEncrypt():boolean {return GetBookInfoListRes.XorEncrypt; }
      getIsKeyBase64():boolean {return GetBookInfoListRes.KeyBase64; }
      getOpcodeName():string {return GetBookInfoListRes.OPCODE_NAME; }
      static OPCODE:number = 86;
      static OPCODE_NAME:string = "GetBookInfoListRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // bookbag.proto 
    export class SubmitBookBagBorrowInfoReq {
      getOpcode():number {return SubmitBookBagBorrowInfoReq.OPCODE; }
      getIsXorEncrypt():boolean {return SubmitBookBagBorrowInfoReq.XorEncrypt; }
      getIsKeyBase64():boolean {return SubmitBookBagBorrowInfoReq.KeyBase64; }
      getOpcodeName():string {return SubmitBookBagBorrowInfoReq.OPCODE_NAME; }
      static OPCODE:number = 89;
      static OPCODE_NAME:string = "SubmitBookBagBorrowInfoReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // bookbag.proto 
    export class SubmitBookBagBorrowInfoRes {
      getOpcode():number {return SubmitBookBagBorrowInfoRes.OPCODE; }
      getIsXorEncrypt():boolean {return SubmitBookBagBorrowInfoRes.XorEncrypt; }
      getIsKeyBase64():boolean {return SubmitBookBagBorrowInfoRes.KeyBase64; }
      getOpcodeName():string {return SubmitBookBagBorrowInfoRes.OPCODE_NAME; }
      static OPCODE:number = 90;
      static OPCODE_NAME:string = "SubmitBookBagBorrowInfoRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // notify.proto 
    export class UserNotifyDataNty {
      getOpcode():number {return UserNotifyDataNty.OPCODE; }
      getIsXorEncrypt():boolean {return UserNotifyDataNty.XorEncrypt; }
      getIsKeyBase64():boolean {return UserNotifyDataNty.KeyBase64; }
      getOpcodeName():string {return UserNotifyDataNty.OPCODE_NAME; }
      static OPCODE:number = 91;
      static OPCODE_NAME:string = "UserNotifyDataNty";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // notify.proto 
    export class AddUserNotifyDataItemNty {
      getOpcode():number {return AddUserNotifyDataItemNty.OPCODE; }
      getIsXorEncrypt():boolean {return AddUserNotifyDataItemNty.XorEncrypt; }
      getIsKeyBase64():boolean {return AddUserNotifyDataItemNty.KeyBase64; }
      getOpcodeName():string {return AddUserNotifyDataItemNty.OPCODE_NAME; }
      static OPCODE:number = 92;
      static OPCODE_NAME:string = "AddUserNotifyDataItemNty";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // notify.proto 
    export class RemoveUserNotifyDataItemNty {
      getOpcode():number {return RemoveUserNotifyDataItemNty.OPCODE; }
      getIsXorEncrypt():boolean {return RemoveUserNotifyDataItemNty.XorEncrypt; }
      getIsKeyBase64():boolean {return RemoveUserNotifyDataItemNty.KeyBase64; }
      getOpcodeName():string {return RemoveUserNotifyDataItemNty.OPCODE_NAME; }
      static OPCODE:number = 93;
      static OPCODE_NAME:string = "RemoveUserNotifyDataItemNty";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // notify.proto 
    export class UserNotifyChangeNty {
      getOpcode():number {return UserNotifyChangeNty.OPCODE; }
      getIsXorEncrypt():boolean {return UserNotifyChangeNty.XorEncrypt; }
      getIsKeyBase64():boolean {return UserNotifyChangeNty.KeyBase64; }
      getOpcodeName():string {return UserNotifyChangeNty.OPCODE_NAME; }
      static OPCODE:number = 94;
      static OPCODE_NAME:string = "UserNotifyChangeNty";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // notify.proto 
    export class ReadNotifyReq {
      getOpcode():number {return ReadNotifyReq.OPCODE; }
      getIsXorEncrypt():boolean {return ReadNotifyReq.XorEncrypt; }
      getIsKeyBase64():boolean {return ReadNotifyReq.KeyBase64; }
      getOpcodeName():string {return ReadNotifyReq.OPCODE_NAME; }
      static OPCODE:number = 95;
      static OPCODE_NAME:string = "ReadNotifyReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // notify.proto 
    export class ReadNotifyRes {
      getOpcode():number {return ReadNotifyRes.OPCODE; }
      getIsXorEncrypt():boolean {return ReadNotifyRes.XorEncrypt; }
      getIsKeyBase64():boolean {return ReadNotifyRes.KeyBase64; }
      getOpcodeName():string {return ReadNotifyRes.OPCODE_NAME; }
      static OPCODE:number = 96;
      static OPCODE_NAME:string = "ReadNotifyRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class GetBookOrderDetailInfoReq {
      getOpcode():number {return GetBookOrderDetailInfoReq.OPCODE; }
      getIsXorEncrypt():boolean {return GetBookOrderDetailInfoReq.XorEncrypt; }
      getIsKeyBase64():boolean {return GetBookOrderDetailInfoReq.KeyBase64; }
      getOpcodeName():string {return GetBookOrderDetailInfoReq.OPCODE_NAME; }
      static OPCODE:number = 97;
      static OPCODE_NAME:string = "GetBookOrderDetailInfoReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class GetBookOrderDetailInfoNty {
      getOpcode():number {return GetBookOrderDetailInfoNty.OPCODE; }
      getIsXorEncrypt():boolean {return GetBookOrderDetailInfoNty.XorEncrypt; }
      getIsKeyBase64():boolean {return GetBookOrderDetailInfoNty.KeyBase64; }
      getOpcodeName():string {return GetBookOrderDetailInfoNty.OPCODE_NAME; }
      static OPCODE:number = 98;
      static OPCODE_NAME:string = "GetBookOrderDetailInfoNty";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class GetBookOrderDetailInfoRes {
      getOpcode():number {return GetBookOrderDetailInfoRes.OPCODE; }
      getIsXorEncrypt():boolean {return GetBookOrderDetailInfoRes.XorEncrypt; }
      getIsKeyBase64():boolean {return GetBookOrderDetailInfoRes.KeyBase64; }
      getOpcodeName():string {return GetBookOrderDetailInfoRes.OPCODE_NAME; }
      static OPCODE:number = 100;
      static OPCODE_NAME:string = "GetBookOrderDetailInfoRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class OutStoreOrderReq {
      getOpcode():number {return OutStoreOrderReq.OPCODE; }
      getIsXorEncrypt():boolean {return OutStoreOrderReq.XorEncrypt; }
      getIsKeyBase64():boolean {return OutStoreOrderReq.KeyBase64; }
      getOpcodeName():string {return OutStoreOrderReq.OPCODE_NAME; }
      static OPCODE:number = 101;
      static OPCODE_NAME:string = "OutStoreOrderReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class OutStoreOrderRes {
      getOpcode():number {return OutStoreOrderRes.OPCODE; }
      getIsXorEncrypt():boolean {return OutStoreOrderRes.XorEncrypt; }
      getIsKeyBase64():boolean {return OutStoreOrderRes.KeyBase64; }
      getOpcodeName():string {return OutStoreOrderRes.OPCODE_NAME; }
      static OPCODE:number = 102;
      static OPCODE_NAME:string = "OutStoreOrderRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class ManagerScanOrderForUserGettingBooksReq {
      getOpcode():number {return ManagerScanOrderForUserGettingBooksReq.OPCODE; }
      getIsXorEncrypt():boolean {return ManagerScanOrderForUserGettingBooksReq.XorEncrypt; }
      getIsKeyBase64():boolean {return ManagerScanOrderForUserGettingBooksReq.KeyBase64; }
      getOpcodeName():string {return ManagerScanOrderForUserGettingBooksReq.OPCODE_NAME; }
      static OPCODE:number = 103;
      static OPCODE_NAME:string = "ManagerScanOrderForUserGettingBooksReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class UserGetBooksOrderConfirmNty {
      getOpcode():number {return UserGetBooksOrderConfirmNty.OPCODE; }
      getIsXorEncrypt():boolean {return UserGetBooksOrderConfirmNty.XorEncrypt; }
      getIsKeyBase64():boolean {return UserGetBooksOrderConfirmNty.KeyBase64; }
      getOpcodeName():string {return UserGetBooksOrderConfirmNty.OPCODE_NAME; }
      static OPCODE:number = 104;
      static OPCODE_NAME:string = "UserGetBooksOrderConfirmNty";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class ManagerScanOrderForUserGettingBooksRes {
      getOpcode():number {return ManagerScanOrderForUserGettingBooksRes.OPCODE; }
      getIsXorEncrypt():boolean {return ManagerScanOrderForUserGettingBooksRes.XorEncrypt; }
      getIsKeyBase64():boolean {return ManagerScanOrderForUserGettingBooksRes.KeyBase64; }
      getOpcodeName():string {return ManagerScanOrderForUserGettingBooksRes.OPCODE_NAME; }
      static OPCODE:number = 105;
      static OPCODE_NAME:string = "ManagerScanOrderForUserGettingBooksRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class UserGetBooksOrderConfirmReq {
      getOpcode():number {return UserGetBooksOrderConfirmReq.OPCODE; }
      getIsXorEncrypt():boolean {return UserGetBooksOrderConfirmReq.XorEncrypt; }
      getIsKeyBase64():boolean {return UserGetBooksOrderConfirmReq.KeyBase64; }
      getOpcodeName():string {return UserGetBooksOrderConfirmReq.OPCODE_NAME; }
      static OPCODE:number = 106;
      static OPCODE_NAME:string = "UserGetBooksOrderConfirmReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class UserGetBooksOrderConfirmRes {
      getOpcode():number {return UserGetBooksOrderConfirmRes.OPCODE; }
      getIsXorEncrypt():boolean {return UserGetBooksOrderConfirmRes.XorEncrypt; }
      getIsKeyBase64():boolean {return UserGetBooksOrderConfirmRes.KeyBase64; }
      getOpcodeName():string {return UserGetBooksOrderConfirmRes.OPCODE_NAME; }
      static OPCODE:number = 107;
      static OPCODE_NAME:string = "UserGetBooksOrderConfirmRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class CancelOrderReq {
      getOpcode():number {return CancelOrderReq.OPCODE; }
      getIsXorEncrypt():boolean {return CancelOrderReq.XorEncrypt; }
      getIsKeyBase64():boolean {return CancelOrderReq.KeyBase64; }
      getOpcodeName():string {return CancelOrderReq.OPCODE_NAME; }
      static OPCODE:number = 108;
      static OPCODE_NAME:string = "CancelOrderReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class CancelOrderRes {
      getOpcode():number {return CancelOrderRes.OPCODE; }
      getIsXorEncrypt():boolean {return CancelOrderRes.XorEncrypt; }
      getIsKeyBase64():boolean {return CancelOrderRes.KeyBase64; }
      getOpcodeName():string {return CancelOrderRes.OPCODE_NAME; }
      static OPCODE:number = 109;
      static OPCODE_NAME:string = "CancelOrderRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // notify.proto 
    export class OnekeyClearNotifyReq {
      getOpcode():number {return OnekeyClearNotifyReq.OPCODE; }
      getIsXorEncrypt():boolean {return OnekeyClearNotifyReq.XorEncrypt; }
      getIsKeyBase64():boolean {return OnekeyClearNotifyReq.KeyBase64; }
      getOpcodeName():string {return OnekeyClearNotifyReq.OPCODE_NAME; }
      static OPCODE:number = 110;
      static OPCODE_NAME:string = "OnekeyClearNotifyReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // notify.proto 
    export class OnekeyClearNotifyRes {
      getOpcode():number {return OnekeyClearNotifyRes.OPCODE; }
      getIsXorEncrypt():boolean {return OnekeyClearNotifyRes.XorEncrypt; }
      getIsKeyBase64():boolean {return OnekeyClearNotifyRes.KeyBase64; }
      getOpcodeName():string {return OnekeyClearNotifyRes.OPCODE_NAME; }
      static OPCODE:number = 111;
      static OPCODE_NAME:string = "OnekeyClearNotifyRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class ReturnBackReq {
      getOpcode():number {return ReturnBackReq.OPCODE; }
      getIsXorEncrypt():boolean {return ReturnBackReq.XorEncrypt; }
      getIsKeyBase64():boolean {return ReturnBackReq.KeyBase64; }
      getOpcodeName():string {return ReturnBackReq.OPCODE_NAME; }
      static OPCODE:number = 112;
      static OPCODE_NAME:string = "ReturnBackReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // library.proto 
    export class ReturnBackRes {
      getOpcode():number {return ReturnBackRes.OPCODE; }
      getIsXorEncrypt():boolean {return ReturnBackRes.XorEncrypt; }
      getIsKeyBase64():boolean {return ReturnBackRes.KeyBase64; }
      getOpcodeName():string {return ReturnBackRes.OPCODE_NAME; }
      static OPCODE:number = 113;
      static OPCODE_NAME:string = "ReturnBackRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // syslog.proto 
    export class SystemLogDataListReq {
      getOpcode():number {return SystemLogDataListReq.OPCODE; }
      getIsXorEncrypt():boolean {return SystemLogDataListReq.XorEncrypt; }
      getIsKeyBase64():boolean {return SystemLogDataListReq.KeyBase64; }
      getOpcodeName():string {return SystemLogDataListReq.OPCODE_NAME; }
      static OPCODE:number = 114;
      static OPCODE_NAME:string = "SystemLogDataListReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // syslog.proto 
    export class SystemLogDataListRes {
      getOpcode():number {return SystemLogDataListRes.OPCODE; }
      getIsXorEncrypt():boolean {return SystemLogDataListRes.XorEncrypt; }
      getIsKeyBase64():boolean {return SystemLogDataListRes.KeyBase64; }
      getOpcodeName():string {return SystemLogDataListRes.OPCODE_NAME; }
      static OPCODE:number = 115;
      static OPCODE_NAME:string = "SystemLogDataListRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // test_opcode.proto 
    export class TestRpcReq {
      getOpcode():number {return TestRpcReq.OPCODE; }
      getIsXorEncrypt():boolean {return TestRpcReq.XorEncrypt; }
      getIsKeyBase64():boolean {return TestRpcReq.KeyBase64; }
      getOpcodeName():string {return TestRpcReq.OPCODE_NAME; }
      static OPCODE:number = 116;
      static OPCODE_NAME:string = "TestRpcReq";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // test_opcode.proto 
    export class TestRpcRes {
      getOpcode():number {return TestRpcRes.OPCODE; }
      getIsXorEncrypt():boolean {return TestRpcRes.XorEncrypt; }
      getIsKeyBase64():boolean {return TestRpcRes.KeyBase64; }
      getOpcodeName():string {return TestRpcRes.OPCODE_NAME; }
      static OPCODE:number = 117;
      static OPCODE_NAME:string = "TestRpcRes";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // broadcast_msg.proto 
    export class SendDataRequest {
      getOpcode():number {return SendDataRequest.OPCODE; }
      getIsXorEncrypt():boolean {return SendDataRequest.XorEncrypt; }
      getIsKeyBase64():boolean {return SendDataRequest.KeyBase64; }
      getOpcodeName():string {return SendDataRequest.OPCODE_NAME; }
      static OPCODE:number = 118;
      static OPCODE_NAME:string = "SendDataRequest";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // broadcast_msg.proto 
    export class SendDataResponse {
      getOpcode():number {return SendDataResponse.OPCODE; }
      getIsXorEncrypt():boolean {return SendDataResponse.XorEncrypt; }
      getIsKeyBase64():boolean {return SendDataResponse.KeyBase64; }
      getOpcodeName():string {return SendDataResponse.OPCODE_NAME; }
      static OPCODE:number = 119;
      static OPCODE_NAME:string = "SendDataResponse";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // broadcast_msg.proto 
    export class BroadcastMsgNty {
      getOpcode():number {return BroadcastMsgNty.OPCODE; }
      getIsXorEncrypt():boolean {return BroadcastMsgNty.XorEncrypt; }
      getIsKeyBase64():boolean {return BroadcastMsgNty.KeyBase64; }
      getOpcodeName():string {return BroadcastMsgNty.OPCODE_NAME; }
      static OPCODE:number = 120;
      static OPCODE_NAME:string = "BroadcastMsgNty";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // broadcast_msg.proto 
    export class BroadcastMsgResponse {
      getOpcode():number {return BroadcastMsgResponse.OPCODE; }
      getIsXorEncrypt():boolean {return BroadcastMsgResponse.XorEncrypt; }
      getIsKeyBase64():boolean {return BroadcastMsgResponse.KeyBase64; }
      getOpcodeName():string {return BroadcastMsgResponse.OPCODE_NAME; }
      static OPCODE:number = 121;
      static OPCODE_NAME:string = "BroadcastMsgResponse";
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    export class TsPbDict {
      static pb_dict = {
          [LoginReq.OPCODE]: new LoginReq(),

          [LoginRes.OPCODE]: new LoginRes(),

          [TestOpcodeReq.OPCODE]: new TestOpcodeReq(),

          [TestOpcodeRes.OPCODE]: new TestOpcodeRes(),

          [TestOpcode2Req.OPCODE]: new TestOpcode2Req(),

          [TestOpcode2Res.OPCODE]: new TestOpcode2Res(),

          [PlayerDataReq.OPCODE]: new PlayerDataReq(),

          [PlayerDataRes.OPCODE]: new PlayerDataRes(),

          [ModifyPlayerNameReq.OPCODE]: new ModifyPlayerNameReq(),

          [ModifyPlayerNameRes.OPCODE]: new ModifyPlayerNameRes(),

          [PlayerDataNty.OPCODE]: new PlayerDataNty(),

          [TitleInfoReq.OPCODE]: new TitleInfoReq(),

          [TitleInfoRes.OPCODE]: new TitleInfoRes(),

          [LoginInfoNty.OPCODE]: new LoginInfoNty(),

          [NodeHeartbeatReq.OPCODE]: new NodeHeartbeatReq(),

          [NodeHeartbeatRes.OPCODE]: new NodeHeartbeatRes(),

          [RegisterNodeReq.OPCODE]: new RegisterNodeReq(),

          [RegisterNodeRes.OPCODE]: new RegisterNodeRes(),

          [GetNodeListReq.OPCODE]: new GetNodeListReq(),

          [GetNodeListRes.OPCODE]: new GetNodeListRes(),

          [ClientHeartbeatReq.OPCODE]: new ClientHeartbeatReq(),

          [ClientHeartbeatRes.OPCODE]: new ClientHeartbeatRes(),

          [LogoutReq.OPCODE]: new LogoutReq(),

          [LogoutNty.OPCODE]: new LogoutNty(),

          [UserClientInfoNty.OPCODE]: new UserClientInfoNty(),

          [GetLibraryInfoReq.OPCODE]: new GetLibraryInfoReq(),

          [GetLibraryInfoRes.OPCODE]: new GetLibraryInfoRes(),

          [CreateLibraryReq.OPCODE]: new CreateLibraryReq(),

          [CreateLibraryRes.OPCODE]: new CreateLibraryRes(),

          [LibraryInfoNty.OPCODE]: new LibraryInfoNty(),

          [JoinLibraryReq.OPCODE]: new JoinLibraryReq(),

          [JoinLibraryRes.OPCODE]: new JoinLibraryRes(),

          [GetLibraryListReq.OPCODE]: new GetLibraryListReq(),

          [GetLibraryListRes.OPCODE]: new GetLibraryListRes(),

          [QuitLibraryReq.OPCODE]: new QuitLibraryReq(),

          [QuitLibraryRes.OPCODE]: new QuitLibraryRes(),

          [TransferLibraianReq.OPCODE]: new TransferLibraianReq(),

          [TransferLibraianRes.OPCODE]: new TransferLibraianRes(),

          [ModifyMemberInfoReq.OPCODE]: new ModifyMemberInfoReq(),

          [ModifyMemberInfoRes.OPCODE]: new ModifyMemberInfoRes(),

          [UserLibraryInfoNty.OPCODE]: new UserLibraryInfoNty(),

          [ModifyUserInfoReq.OPCODE]: new ModifyUserInfoReq(),

          [ModifyUserInfoRes.OPCODE]: new ModifyUserInfoRes(),

          [LoginFinishReq.OPCODE]: new LoginFinishReq(),

          [LoginFinishRes.OPCODE]: new LoginFinishRes(),

          [GetLibraryMemberSimpleInfoReq.OPCODE]: new GetLibraryMemberSimpleInfoReq(),

          [GetLibraryMemberSimpleInfoRes.OPCODE]: new GetLibraryMemberSimpleInfoRes(),

          [AddLibraryBookReq.OPCODE]: new AddLibraryBookReq(),

          [AddLibraryBookRes.OPCODE]: new AddLibraryBookRes(),

          [AddLibraryBookCountReq.OPCODE]: new AddLibraryBookCountReq(),

          [AddLibraryBookCountRes.OPCODE]: new AddLibraryBookCountRes(),

          [GetBookListReq.OPCODE]: new GetBookListReq(),

          [BookListNty.OPCODE]: new BookListNty(),

          [BooksChangeNty.OPCODE]: new BooksChangeNty(),

          [GetBookListRes.OPCODE]: new GetBookListRes(),

          [BookVariantInfoItemsNty.OPCODE]: new BookVariantInfoItemsNty(),

          [GetBookInfoReq.OPCODE]: new GetBookInfoReq(),

          [GetBookInfoRes.OPCODE]: new GetBookInfoRes(),

          [GetBookByBookNameReq.OPCODE]: new GetBookByBookNameReq(),

          [GetBookByBookNameRes.OPCODE]: new GetBookByBookNameRes(),

          [BookBagInfoReq.OPCODE]: new BookBagInfoReq(),

          [BookBagInfoNty.OPCODE]: new BookBagInfoNty(),

          [BookBagInfoRes.OPCODE]: new BookBagInfoRes(),

          [SetBookBagInfoReq.OPCODE]: new SetBookBagInfoReq(),

          [SetBookBagInfoRes.OPCODE]: new SetBookBagInfoRes(),

          [GetBookInfoListReq.OPCODE]: new GetBookInfoListReq(),

          [GetBookInfoListRes.OPCODE]: new GetBookInfoListRes(),

          [SubmitBookBagBorrowInfoReq.OPCODE]: new SubmitBookBagBorrowInfoReq(),

          [SubmitBookBagBorrowInfoRes.OPCODE]: new SubmitBookBagBorrowInfoRes(),

          [UserNotifyDataNty.OPCODE]: new UserNotifyDataNty(),

          [AddUserNotifyDataItemNty.OPCODE]: new AddUserNotifyDataItemNty(),

          [RemoveUserNotifyDataItemNty.OPCODE]: new RemoveUserNotifyDataItemNty(),

          [UserNotifyChangeNty.OPCODE]: new UserNotifyChangeNty(),

          [ReadNotifyReq.OPCODE]: new ReadNotifyReq(),

          [ReadNotifyRes.OPCODE]: new ReadNotifyRes(),

          [GetBookOrderDetailInfoReq.OPCODE]: new GetBookOrderDetailInfoReq(),

          [GetBookOrderDetailInfoNty.OPCODE]: new GetBookOrderDetailInfoNty(),

          [GetBookOrderDetailInfoRes.OPCODE]: new GetBookOrderDetailInfoRes(),

          [OutStoreOrderReq.OPCODE]: new OutStoreOrderReq(),

          [OutStoreOrderRes.OPCODE]: new OutStoreOrderRes(),

          [ManagerScanOrderForUserGettingBooksReq.OPCODE]: new ManagerScanOrderForUserGettingBooksReq(),

          [UserGetBooksOrderConfirmNty.OPCODE]: new UserGetBooksOrderConfirmNty(),

          [ManagerScanOrderForUserGettingBooksRes.OPCODE]: new ManagerScanOrderForUserGettingBooksRes(),

          [UserGetBooksOrderConfirmReq.OPCODE]: new UserGetBooksOrderConfirmReq(),

          [UserGetBooksOrderConfirmRes.OPCODE]: new UserGetBooksOrderConfirmRes(),

          [CancelOrderReq.OPCODE]: new CancelOrderReq(),

          [CancelOrderRes.OPCODE]: new CancelOrderRes(),

          [OnekeyClearNotifyReq.OPCODE]: new OnekeyClearNotifyReq(),

          [OnekeyClearNotifyRes.OPCODE]: new OnekeyClearNotifyRes(),

          [ReturnBackReq.OPCODE]: new ReturnBackReq(),

          [ReturnBackRes.OPCODE]: new ReturnBackRes(),

          [SystemLogDataListReq.OPCODE]: new SystemLogDataListReq(),

          [SystemLogDataListRes.OPCODE]: new SystemLogDataListRes(),

          [TestRpcReq.OPCODE]: new TestRpcReq(),

          [TestRpcRes.OPCODE]: new TestRpcRes(),

          [SendDataRequest.OPCODE]: new SendDataRequest(),

          [SendDataResponse.OPCODE]: new SendDataResponse(),

          [BroadcastMsgNty.OPCODE]: new BroadcastMsgNty(),

          [BroadcastMsgResponse.OPCODE]: new BroadcastMsgResponse()


      }

    }
}