/*!
*  MIT License
*  
*  Copyright (c) 2020 ericyonng<120453674@qq.com>
*  
*  Permission is hereby granted, free of charge, to any person obtaining a copy
*  of this software and associated documentation files (the "Software"), to deal
*  in the Software without restriction, including without limitation the rights
*  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*  copies of the Software, and to permit persons to whom the Software is
*  furnished to do so, subject to the following conditions:
*  
*  The above copyright notice and this permission notice shall be included in all
*  copies or substantial portions of the Software.
*  
*  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
*  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
*  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
*  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
*  SOFTWARE.
* 
* Author: Eric Yonng
* Description: Generated By protogentool, Dont Modify This File!!!
*/


export namespace ts_pbinfo{

    // login.proto 
    export class LoginReq {
      getOpcode():number {return LoginReq.OPCODE; }
      getIsXorEncrypt():boolean {return LoginReq.XorEncrypt; }
      getIsKeyBase64():boolean {return LoginReq.KeyBase64; }
      static OPCODE:number = 1;
      static XorEncrypt:boolean = true;
      static KeyBase64:boolean = true;
    }


    // login.proto 
    export class LoginRes {
      getOpcode():number {return LoginRes.OPCODE; }
      getIsXorEncrypt():boolean {return LoginRes.XorEncrypt; }
      getIsKeyBase64():boolean {return LoginRes.KeyBase64; }
      static OPCODE:number = 2;
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // test_opcode.proto 
    export class TestOpcodeReq {
      getOpcode():number {return TestOpcodeReq.OPCODE; }
      getIsXorEncrypt():boolean {return TestOpcodeReq.XorEncrypt; }
      getIsKeyBase64():boolean {return TestOpcodeReq.KeyBase64; }
      static OPCODE:number = 3;
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // test_opcode.proto 
    export class TestOpcodeRes {
      getOpcode():number {return TestOpcodeRes.OPCODE; }
      getIsXorEncrypt():boolean {return TestOpcodeRes.XorEncrypt; }
      getIsKeyBase64():boolean {return TestOpcodeRes.KeyBase64; }
      static OPCODE:number = 4;
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // test_opcode.proto 
    export class TestOpcode2Req {
      getOpcode():number {return TestOpcode2Req.OPCODE; }
      getIsXorEncrypt():boolean {return TestOpcode2Req.XorEncrypt; }
      getIsKeyBase64():boolean {return TestOpcode2Req.KeyBase64; }
      static OPCODE:number = 5;
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // test_opcode.proto 
    export class TestOpcode2Res {
      getOpcode():number {return TestOpcode2Res.OPCODE; }
      getIsXorEncrypt():boolean {return TestOpcode2Res.XorEncrypt; }
      getIsKeyBase64():boolean {return TestOpcode2Res.KeyBase64; }
      static OPCODE:number = 6;
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // player.proto 
    export class PlayerDataReq {
      getOpcode():number {return PlayerDataReq.OPCODE; }
      getIsXorEncrypt():boolean {return PlayerDataReq.XorEncrypt; }
      getIsKeyBase64():boolean {return PlayerDataReq.KeyBase64; }
      static OPCODE:number = 7;
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // player.proto 
    export class PlayerDataRes {
      getOpcode():number {return PlayerDataRes.OPCODE; }
      getIsXorEncrypt():boolean {return PlayerDataRes.XorEncrypt; }
      getIsKeyBase64():boolean {return PlayerDataRes.KeyBase64; }
      static OPCODE:number = 8;
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // player.proto 
    export class ModifyPlayerNameReq {
      getOpcode():number {return ModifyPlayerNameReq.OPCODE; }
      getIsXorEncrypt():boolean {return ModifyPlayerNameReq.XorEncrypt; }
      getIsKeyBase64():boolean {return ModifyPlayerNameReq.KeyBase64; }
      static OPCODE:number = 9;
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // player.proto 
    export class ModifyPlayerNameRes {
      getOpcode():number {return ModifyPlayerNameRes.OPCODE; }
      getIsXorEncrypt():boolean {return ModifyPlayerNameRes.XorEncrypt; }
      getIsKeyBase64():boolean {return ModifyPlayerNameRes.KeyBase64; }
      static OPCODE:number = 10;
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // player.proto 
    export class PlayerDataNty {
      getOpcode():number {return PlayerDataNty.OPCODE; }
      getIsXorEncrypt():boolean {return PlayerDataNty.XorEncrypt; }
      getIsKeyBase64():boolean {return PlayerDataNty.KeyBase64; }
      static OPCODE:number = 11;
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // title.proto 
    export class TitleInfoReq {
      getOpcode():number {return TitleInfoReq.OPCODE; }
      getIsXorEncrypt():boolean {return TitleInfoReq.XorEncrypt; }
      getIsKeyBase64():boolean {return TitleInfoReq.KeyBase64; }
      static OPCODE:number = 20;
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // title.proto 
    export class TitleInfoRes {
      getOpcode():number {return TitleInfoRes.OPCODE; }
      getIsXorEncrypt():boolean {return TitleInfoRes.XorEncrypt; }
      getIsKeyBase64():boolean {return TitleInfoRes.KeyBase64; }
      static OPCODE:number = 21;
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // login.proto 
    export class LoginInfoNty {
      getOpcode():number {return LoginInfoNty.OPCODE; }
      getIsXorEncrypt():boolean {return LoginInfoNty.XorEncrypt; }
      getIsKeyBase64():boolean {return LoginInfoNty.KeyBase64; }
      static OPCODE:number = 22;
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // heartbeat.proto 
    export class NodeHeartbeatReq {
      getOpcode():number {return NodeHeartbeatReq.OPCODE; }
      getIsXorEncrypt():boolean {return NodeHeartbeatReq.XorEncrypt; }
      getIsKeyBase64():boolean {return NodeHeartbeatReq.KeyBase64; }
      static OPCODE:number = 23;
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // heartbeat.proto 
    export class NodeHeartbeatRes {
      getOpcode():number {return NodeHeartbeatRes.OPCODE; }
      getIsXorEncrypt():boolean {return NodeHeartbeatRes.XorEncrypt; }
      getIsKeyBase64():boolean {return NodeHeartbeatRes.KeyBase64; }
      static OPCODE:number = 24;
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // heartbeat.proto 
    export class RegisterNodeReq {
      getOpcode():number {return RegisterNodeReq.OPCODE; }
      getIsXorEncrypt():boolean {return RegisterNodeReq.XorEncrypt; }
      getIsKeyBase64():boolean {return RegisterNodeReq.KeyBase64; }
      static OPCODE:number = 25;
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // heartbeat.proto 
    export class RegisterNodeRes {
      getOpcode():number {return RegisterNodeRes.OPCODE; }
      getIsXorEncrypt():boolean {return RegisterNodeRes.XorEncrypt; }
      getIsKeyBase64():boolean {return RegisterNodeRes.KeyBase64; }
      static OPCODE:number = 26;
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // heartbeat.proto 
    export class GetNodeListReq {
      getOpcode():number {return GetNodeListReq.OPCODE; }
      getIsXorEncrypt():boolean {return GetNodeListReq.XorEncrypt; }
      getIsKeyBase64():boolean {return GetNodeListReq.KeyBase64; }
      static OPCODE:number = 27;
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // heartbeat.proto 
    export class GetNodeListRes {
      getOpcode():number {return GetNodeListRes.OPCODE; }
      getIsXorEncrypt():boolean {return GetNodeListRes.XorEncrypt; }
      getIsKeyBase64():boolean {return GetNodeListRes.KeyBase64; }
      static OPCODE:number = 28;
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // heartbeat.proto 
    export class ClientHeartbeatReq {
      getOpcode():number {return ClientHeartbeatReq.OPCODE; }
      getIsXorEncrypt():boolean {return ClientHeartbeatReq.XorEncrypt; }
      getIsKeyBase64():boolean {return ClientHeartbeatReq.KeyBase64; }
      static OPCODE:number = 29;
      static XorEncrypt:boolean = true;
      static KeyBase64:boolean = true;
    }


    // heartbeat.proto 
    export class ClientHeartbeatRes {
      getOpcode():number {return ClientHeartbeatRes.OPCODE; }
      getIsXorEncrypt():boolean {return ClientHeartbeatRes.XorEncrypt; }
      getIsKeyBase64():boolean {return ClientHeartbeatRes.KeyBase64; }
      static OPCODE:number = 30;
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // login.proto 
    export class LogoutReq {
      getOpcode():number {return LogoutReq.OPCODE; }
      getIsXorEncrypt():boolean {return LogoutReq.XorEncrypt; }
      getIsKeyBase64():boolean {return LogoutReq.KeyBase64; }
      static OPCODE:number = 31;
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    // login.proto 
    export class LogoutNty {
      getOpcode():number {return LogoutNty.OPCODE; }
      getIsXorEncrypt():boolean {return LogoutNty.XorEncrypt; }
      getIsKeyBase64():boolean {return LogoutNty.KeyBase64; }
      static OPCODE:number = 32;
      static XorEncrypt:boolean = false;
      static KeyBase64:boolean = false;
    }


    export class TsPbDict {
      static pb_dict = {
          [LoginReq.OPCODE]: new LoginReq(),

          [LoginRes.OPCODE]: new LoginRes(),

          [TestOpcodeReq.OPCODE]: new TestOpcodeReq(),

          [TestOpcodeRes.OPCODE]: new TestOpcodeRes(),

          [TestOpcode2Req.OPCODE]: new TestOpcode2Req(),

          [TestOpcode2Res.OPCODE]: new TestOpcode2Res(),

          [PlayerDataReq.OPCODE]: new PlayerDataReq(),

          [PlayerDataRes.OPCODE]: new PlayerDataRes(),

          [ModifyPlayerNameReq.OPCODE]: new ModifyPlayerNameReq(),

          [ModifyPlayerNameRes.OPCODE]: new ModifyPlayerNameRes(),

          [PlayerDataNty.OPCODE]: new PlayerDataNty(),

          [TitleInfoReq.OPCODE]: new TitleInfoReq(),

          [TitleInfoRes.OPCODE]: new TitleInfoRes(),

          [LoginInfoNty.OPCODE]: new LoginInfoNty(),

          [NodeHeartbeatReq.OPCODE]: new NodeHeartbeatReq(),

          [NodeHeartbeatRes.OPCODE]: new NodeHeartbeatRes(),

          [RegisterNodeReq.OPCODE]: new RegisterNodeReq(),

          [RegisterNodeRes.OPCODE]: new RegisterNodeRes(),

          [GetNodeListReq.OPCODE]: new GetNodeListReq(),

          [GetNodeListRes.OPCODE]: new GetNodeListRes(),

          [ClientHeartbeatReq.OPCODE]: new ClientHeartbeatReq(),

          [ClientHeartbeatRes.OPCODE]: new ClientHeartbeatRes(),

          [LogoutReq.OPCODE]: new LogoutReq(),

          [LogoutNty.OPCODE]: new LogoutNty()


      }

    }
}