/*!
*  MIT License
*  
*  Copyright (c) 2020 ericyonng<120453674@qq.com>
*  
*  Permission is hereby granted, free of charge, to any person obtaining a copy
*  of this software and associated documentation files (the "Software"), to deal
*  in the Software without restriction, including without limitation the rights
*  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*  copies of the Software, and to permit persons to whom the Software is
*  furnished to do so, subject to the following conditions:
*  
*  The above copyright notice and this permission notice shall be included in all
*  copies or substantial portions of the Software.
*  
*  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
*  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
*  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
*  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
*  SOFTWARE.
* 
* Author: Eric Yonng
* Description: Generated By protogentool, Dont Modify This File!!!
*/


#ifndef __PROTOCOLS_ALLPBS_H__
#define __PROTOCOLS_ALLPBS_H__

#pragma once

#include <protocols/cplusplus/library/bookbag.pb.h>
#include <protocols/cplusplus/com.pb.h>
#include <protocols/cplusplus/library/com_book.pb.h>
#include <protocols/cplusplus/library/com_bookbag.pb.h>
#include <protocols/cplusplus/com_client_user.pb.h>
#include <protocols/cplusplus/com_heartbeat.pb.h>
#include <protocols/cplusplus/library/com_library.pb.h>
#include <protocols/cplusplus/com_login.pb.h>
#include <protocols/cplusplus/library/com_notify.pb.h>
#include <protocols/cplusplus/library/com_offline.pb.h>
#include <protocols/cplusplus/com_passtime.pb.h>
#include <protocols/cplusplus/com_player.pb.h>
#include <protocols/cplusplus/library/com_syslog.pb.h>
#include <protocols/cplusplus/com_system_table.pb.h>
#include <protocols/cplusplus/com_title.pb.h>
#include <protocols/cplusplus/com_user.pb.h>
#include <protocols/cplusplus/library/com_variant.pb.h>
#include <protocols/cplusplus/comp_test.pb.h>
#include <protocols/cplusplus/heartbeat.pb.h>
#include <protocols/cplusplus/library/library.pb.h>
#include <protocols/cplusplus/login.pb.h>
#include <protocols/cplusplus/library/notify.pb.h>
#include <protocols/cplusplus/player.pb.h>
#include <protocols/cplusplus/library/syslog.pb.h>
#include <protocols/cplusplus/test_opcode.pb.h>
#include <protocols/cplusplus/title.pb.h>
#include <protocols/cplusplus/user.pb.h>

#endif // __PROTOCOLS_ALLPBS_H__
