/*!
*  MIT License
*  
*  Copyright (c) 2020 ericyonng<120453674@qq.com>
*  
*  Permission is hereby granted, free of charge, to any person obtaining a copy
*  of this software and associated documentation files (the "Software"), to deal
*  in the Software without restriction, including without limitation the rights
*  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*  copies of the Software, and to permit persons to whom the Software is
*  furnished to do so, subject to the following conditions:
*  
*  The above copyright notice and this permission notice shall be included in all
*  copies or substantial portions of the Software.
*  
*  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
*  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
*  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
*  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
*  SOFTWARE.
* 
* Author: Eric Yonng
* Description: Generated By protogentool, Dont Modify This File!!!
*/


#ifndef __PROTOCOLS_ORM_OUT_ALL_ORM_DATAS_H__
#define __PROTOCOLS_ORM_OUT_ALL_ORM_DATAS_H__

#pragma once

#include <protocols/orm_out/SimpleInfoOrmData.h>
#include <protocols/orm_out/TestOrmOrmData.h>
#include <protocols/orm_out/UserBaseInfoOrmData.h>
#include <protocols/orm_out/BookBagInfoOrmData.h>
#include <protocols/orm_out/LibraryInfoOrmData.h>
#include <protocols/orm_out/TestCustomDataOrmData.h>
#include <protocols/orm_out/BookInfoItemOrmData.h>
#include <protocols/orm_out/LibararyManagerInfoOrmData.h>
#include <protocols/orm_out/MemberInfoOrmData.h>
#include <protocols/orm_out/BorrowOrderInfoOrmData.h>
#include <protocols/orm_out/BorrowBookInfoOrmData.h>
#include <protocols/orm_out/CancelOrderReasonOrmData.h>
#include <protocols/orm_out/BookInfoOrmData.h>
#include <protocols/orm_out/BookVariantInfoOrmData.h>
#include <protocols/orm_out/SnapshotClientInfoOrmData.h>

#endif // __PROTOCOLS_ORM_OUT_ALL_ORM_DATAS_H__