/*!
*  MIT License
*  
*  Copyright (c) 2020 ericyonng<120453674@qq.com>
*  
*  Permission is hereby granted, free of charge, to any person obtaining a copy
*  of this software and associated documentation files (the "Software"), to deal
*  in the Software without restriction, including without limitation the rights
*  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*  copies of the Software, and to permit persons to whom the Software is
*  furnished to do so, subject to the following conditions:
*  
*  The above copyright notice and this permission notice shall be included in all
*  copies or substantial portions of the Software.
*  
*  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
*  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
*  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
*  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
*  SOFTWARE.
* 
* Author: Eric Yonng
* Description: Generated By protogentool, Dont Modify This File!!!
*/


#include "pch.h"
#include <protocols/cplusplus/library/com_book.pb.h>
#include <protocols/orm_out/BookVariantInfoOrmData.h>

SERVICE_COMMON_BEGIN

POOL_CREATE_OBJ_DEFAULT_IMPL(BookVariantInfoOrmData);

BookVariantInfoOrmData::BookVariantInfoOrmData()
:_ormRawPbData(new ::CRYSTAL_NET::service::BookVariantInfo)
{
}

BookVariantInfoOrmData::BookVariantInfoOrmData(::CRYSTAL_NET::service::BookVariantInfo *pb)
:_ormRawPbData(NULL)
{
    AttachPb(pb);
}

BookVariantInfoOrmData::BookVariantInfoOrmData(const BookVariantInfoOrmData &other)
:IOrmData(reinterpret_cast<const IOrmData &>(other))
,_ormRawPbData(other._ormRawPbData ? new ::CRYSTAL_NET::service::BookVariantInfo(*other._ormRawPbData) : NULL)
{
}

BookVariantInfoOrmData::BookVariantInfoOrmData(BookVariantInfoOrmData &&other)
:IOrmData(std::forward<IOrmData>(other))
,_ormRawPbData(other._ormRawPbData)
{
    other._ormRawPbData = NULL;
}

BookVariantInfoOrmData::BookVariantInfoOrmData(const ::CRYSTAL_NET::service::BookVariantInfo &pb)
:_ormRawPbData(new ::CRYSTAL_NET::service::BookVariantInfo(pb))
{

}

BookVariantInfoOrmData::~BookVariantInfoOrmData()
{
    if(LIKELY(!IsAttachPb()))
        CRYSTAL_RELEASE_SAFE(_ormRawPbData);
}

void BookVariantInfoOrmData::Release()
{
    BookVariantInfoOrmData::DeleteThreadLocal_BookVariantInfoOrmData(this);
}

BookVariantInfoOrmData &BookVariantInfoOrmData::operator =(const ::CRYSTAL_NET::service::BookVariantInfo &pb)
{
    CRYSTAL_RELEASE_SAFE(_ormRawPbData);
    _ormRawPbData = new ::CRYSTAL_NET::service::BookVariantInfo(pb);
    _MaskDirty(true);
    return *this;
}

BookVariantInfoOrmData &BookVariantInfoOrmData::operator =(const BookVariantInfoOrmData &other)
{
    if(this == &other)
        return *this;

    IOrmData::operator =(reinterpret_cast<const IOrmData &>(other));
    CRYSTAL_RELEASE_SAFE(_ormRawPbData);
    if(other._ormRawPbData)
        _ormRawPbData = new ::CRYSTAL_NET::service::BookVariantInfo(*other._ormRawPbData);
    if(_ormRawPbData)
    {
    }
    _MaskDirty(true);

    return *this;
}

BookVariantInfoOrmData &BookVariantInfoOrmData::operator =(BookVariantInfoOrmData &&other)
{
    if(this == &other)
        return *this;

    IOrmData::operator =(std::forward<IOrmData>(other));
    _ormRawPbData = other._ormRawPbData;
    other._ormRawPbData = NULL;


    return *this;
}

void BookVariantInfoOrmData::Clear()
{

    if(_ormRawPbData)
        _ormRawPbData->Clear();

    _MaskDirty(true);
}

void BookVariantInfoOrmData::_AttachPb(void *pb)
{
    if(LIKELY(!IsAttachPb()))
        CRYSTAL_RELEASE_SAFE(_ormRawPbData);

    _ormRawPbData = reinterpret_cast<::CRYSTAL_NET::service::BookVariantInfo *>(pb);


}

KERNEL_NS::LibString BookVariantInfoOrmData::ToJsonString() const
{
    return _ormRawPbData->ToJsonString();
}

bool BookVariantInfoOrmData::ToJsonString(std::string *data) const
{
    return _ormRawPbData->ToJsonString(data);
}

bool BookVariantInfoOrmData::FromJsonString(const Byte8 *data, size_t len)
{
    return _ormRawPbData->FromJsonString(data, len);
}

const ::CRYSTAL_NET::service::BookVariantInfo *BookVariantInfoOrmData::GetPbRawData() const
{
    return _ormRawPbData;
}

void BookVariantInfoOrmData::clear_count()
{
    _ormRawPbData->clear_count();
    _MaskDirty(true);
}

int64_t BookVariantInfoOrmData::count() const
{
    return _ormRawPbData->count();
}

void BookVariantInfoOrmData::set_count(int64_t value)
{
    _ormRawPbData->set_count(value);
    _MaskDirty(true);
}

void BookVariantInfoOrmData::clear_price()
{
    _ormRawPbData->clear_price();
    _MaskDirty(true);
}

int64_t BookVariantInfoOrmData::price() const
{
    return _ormRawPbData->price();
}

void BookVariantInfoOrmData::set_price(int64_t value)
{
    _ormRawPbData->set_price(value);
    _MaskDirty(true);
}

bool BookVariantInfoOrmData::_OnEncode(KERNEL_NS::LibStream<KERNEL_NS::_Build::MT> &stream) const
{
    return _ormRawPbData->Encode(stream);
}

bool BookVariantInfoOrmData::_OnEncode(KERNEL_NS::LibStream<KERNEL_NS::_Build::TL> &stream) const
{
    return _ormRawPbData->Encode(stream);
}

bool BookVariantInfoOrmData::_OnDecode(KERNEL_NS::LibStream<KERNEL_NS::_Build::MT> &stream)
{
    return _ormRawPbData->Decode(stream);
}

bool BookVariantInfoOrmData::_OnDecode(KERNEL_NS::LibStream<KERNEL_NS::_Build::TL> &stream)
{
    return _ormRawPbData->Decode(stream);
}

POOL_CREATE_OBJ_DEFAULT_IMPL(BookVariantInfoOrmDataFactory);

IOrmData *BookVariantInfoOrmDataFactory::Create() const
{
    return BookVariantInfoOrmData::NewThreadLocal_BookVariantInfoOrmData();
}


SERVICE_COMMON_END
