/*!
*  MIT License
*  
*  Copyright (c) 2020 ericyonng<120453674@qq.com>
*  
*  Permission is hereby granted, free of charge, to any person obtaining a copy
*  of this software and associated documentation files (the "Software"), to deal
*  in the Software without restriction, including without limitation the rights
*  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*  copies of the Software, and to permit persons to whom the Software is
*  furnished to do so, subject to the following conditions:
*  
*  The above copyright notice and this permission notice shall be included in all
*  copies or substantial portions of the Software.
*  
*  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
*  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
*  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
*  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
*  SOFTWARE.
* 
* Author: Eric Yonng
* Description: Generated By protogentool, Dont Modify This File!!!
*/


#include "pch.h"
#include <protocols/cplusplus/library/com_bookbag.pb.h>
#include <protocols/orm_out/BookInfoItemOrmData.h>

SERVICE_COMMON_BEGIN

POOL_CREATE_OBJ_DEFAULT_IMPL(BookInfoItemOrmData);

BookInfoItemOrmData::BookInfoItemOrmData()
:_ormRawPbData(new ::CRYSTAL_NET::service::BookInfoItem)
{
}

BookInfoItemOrmData::BookInfoItemOrmData(::CRYSTAL_NET::service::BookInfoItem *pb)
:_ormRawPbData(NULL)
{
    AttachPb(pb);
}

BookInfoItemOrmData::BookInfoItemOrmData(const BookInfoItemOrmData &other)
:IOrmData(reinterpret_cast<const IOrmData &>(other))
,_ormRawPbData(other._ormRawPbData ? new ::CRYSTAL_NET::service::BookInfoItem(*other._ormRawPbData) : NULL)
{
}

BookInfoItemOrmData::BookInfoItemOrmData(BookInfoItemOrmData &&other)
:IOrmData(std::forward<IOrmData>(other))
,_ormRawPbData(other._ormRawPbData)
{
    other._ormRawPbData = NULL;
}

BookInfoItemOrmData::BookInfoItemOrmData(const ::CRYSTAL_NET::service::BookInfoItem &pb)
:_ormRawPbData(new ::CRYSTAL_NET::service::BookInfoItem(pb))
{

}

BookInfoItemOrmData::~BookInfoItemOrmData()
{
    if(LIKELY(!IsAttachPb()))
        CRYSTAL_RELEASE_SAFE(_ormRawPbData);
}

void BookInfoItemOrmData::Release()
{
    BookInfoItemOrmData::DeleteThreadLocal_BookInfoItemOrmData(this);
}

BookInfoItemOrmData &BookInfoItemOrmData::operator =(const ::CRYSTAL_NET::service::BookInfoItem &pb)
{
    CRYSTAL_RELEASE_SAFE(_ormRawPbData);
    _ormRawPbData = new ::CRYSTAL_NET::service::BookInfoItem(pb);
    _MaskDirty(true);
    return *this;
}

BookInfoItemOrmData &BookInfoItemOrmData::operator =(const BookInfoItemOrmData &other)
{
    if(this == &other)
        return *this;

    IOrmData::operator =(reinterpret_cast<const IOrmData &>(other));
    CRYSTAL_RELEASE_SAFE(_ormRawPbData);
    if(other._ormRawPbData)
        _ormRawPbData = new ::CRYSTAL_NET::service::BookInfoItem(*other._ormRawPbData);
    if(_ormRawPbData)
    {
    }
    _MaskDirty(true);

    return *this;
}

BookInfoItemOrmData &BookInfoItemOrmData::operator =(BookInfoItemOrmData &&other)
{
    if(this == &other)
        return *this;

    IOrmData::operator =(std::forward<IOrmData>(other));
    _ormRawPbData = other._ormRawPbData;
    other._ormRawPbData = NULL;


    return *this;
}

void BookInfoItemOrmData::Clear()
{

    if(_ormRawPbData)
        _ormRawPbData->Clear();

    _MaskDirty(true);
}

void BookInfoItemOrmData::_AttachPb(void *pb)
{
    if(LIKELY(!IsAttachPb()))
        CRYSTAL_RELEASE_SAFE(_ormRawPbData);

    _ormRawPbData = reinterpret_cast<::CRYSTAL_NET::service::BookInfoItem *>(pb);


}

KERNEL_NS::LibString BookInfoItemOrmData::ToJsonString() const
{
    return _ormRawPbData->ToJsonString();
}

bool BookInfoItemOrmData::ToJsonString(std::string *data) const
{
    return _ormRawPbData->ToJsonString(data);
}

bool BookInfoItemOrmData::FromJsonString(const Byte8 *data, size_t len)
{
    return _ormRawPbData->FromJsonString(data, len);
}

const ::CRYSTAL_NET::service::BookInfoItem *BookInfoItemOrmData::GetPbRawData() const
{
    return _ormRawPbData;
}

void BookInfoItemOrmData::clear_bookid()
{
    _ormRawPbData->clear_bookid();
    _MaskDirty(true);
}

uint64_t BookInfoItemOrmData::bookid() const
{
    return _ormRawPbData->bookid();
}

void BookInfoItemOrmData::set_bookid(uint64_t value)
{
    _ormRawPbData->set_bookid(value);
    _MaskDirty(true);
}

void BookInfoItemOrmData::clear_bookcount()
{
    _ormRawPbData->clear_bookcount();
    _MaskDirty(true);
}

int32_t BookInfoItemOrmData::bookcount() const
{
    return _ormRawPbData->bookcount();
}

void BookInfoItemOrmData::set_bookcount(int32_t value)
{
    _ormRawPbData->set_bookcount(value);
    _MaskDirty(true);
}

void BookInfoItemOrmData::clear_borrowdays()
{
    _ormRawPbData->clear_borrowdays();
    _MaskDirty(true);
}

int32_t BookInfoItemOrmData::borrowdays() const
{
    return _ormRawPbData->borrowdays();
}

void BookInfoItemOrmData::set_borrowdays(int32_t value)
{
    _ormRawPbData->set_borrowdays(value);
    _MaskDirty(true);
}

bool BookInfoItemOrmData::_OnEncode(KERNEL_NS::LibStream<KERNEL_NS::_Build::MT> &stream) const
{
    return _ormRawPbData->Encode(stream);
}

bool BookInfoItemOrmData::_OnEncode(KERNEL_NS::LibStream<KERNEL_NS::_Build::TL> &stream) const
{
    return _ormRawPbData->Encode(stream);
}

bool BookInfoItemOrmData::_OnDecode(KERNEL_NS::LibStream<KERNEL_NS::_Build::MT> &stream)
{
    return _ormRawPbData->Decode(stream);
}

bool BookInfoItemOrmData::_OnDecode(KERNEL_NS::LibStream<KERNEL_NS::_Build::TL> &stream)
{
    return _ormRawPbData->Decode(stream);
}

POOL_CREATE_OBJ_DEFAULT_IMPL(BookInfoItemOrmDataFactory);

IOrmData *BookInfoItemOrmDataFactory::Create() const
{
    return BookInfoItemOrmData::NewThreadLocal_BookInfoItemOrmData();
}


SERVICE_COMMON_END
