/*!
*  MIT License
*  
*  Copyright (c) 2020 ericyonng<120453674@qq.com>
*  
*  Permission is hereby granted, free of charge, to any person obtaining a copy
*  of this software and associated documentation files (the "Software"), to deal
*  in the Software without restriction, including without limitation the rights
*  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*  copies of the Software, and to permit persons to whom the Software is
*  furnished to do so, subject to the following conditions:
*  
*  The above copyright notice and this permission notice shall be included in all
*  copies or substantial portions of the Software.
*  
*  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
*  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
*  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
*  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
*  SOFTWARE.
* 
* Author: Eric Yonng
* Description: Generated By protogentool, Dont Modify This File!!!
*/


#ifndef __PROTOCOLS_ORM_OUT_BOOKBAGINFOORMDATA_H__
#define __PROTOCOLS_ORM_OUT_BOOKBAGINFOORMDATA_H__

#pragma once
#include <kernel/kernel.h>
#include <service_common/protocol/ORM/IOrmData.h>

#include <vector>


namespace CRYSTAL_NET {
namespace service {

class BookBagInfo;
class BookInfoItem;

}
}

namespace google {
    namespace protobuf {
template <typename Element>
class RepeatedPtrField;


    }
}

SERVICE_COMMON_BEGIN

class BookInfoItemOrmData;

SERVICE_COMMON_END

SERVICE_COMMON_BEGIN

class BookBagInfoOrmData : public SERVICE_COMMON_NS::IOrmData
{
    POOL_CREATE_OBJ_DEFAULT_P1(IOrmData, BookBagInfoOrmData)

public:
    BookBagInfoOrmData();
    BookBagInfoOrmData(::CRYSTAL_NET::service::BookBagInfo *pb);
    BookBagInfoOrmData(const BookBagInfoOrmData &other);
    BookBagInfoOrmData(BookBagInfoOrmData &&other);
    BookBagInfoOrmData(const ::CRYSTAL_NET::service::BookBagInfo &pb);
    ~BookBagInfoOrmData();

    virtual void Release() override;

    BookBagInfoOrmData &operator =(const ::CRYSTAL_NET::service::BookBagInfo &pb);

    BookBagInfoOrmData &operator =(const BookBagInfoOrmData &other);

    BookBagInfoOrmData &operator =(BookBagInfoOrmData &&other);

    virtual KERNEL_NS::LibString ToJsonString() const override;

    virtual bool ToJsonString(std::string *data) const override;

    virtual bool FromJsonString(const Byte8 *data, size_t len) override;

    virtual Int64 GetOrmId() const override{ return 9; }

    void Clear();
    const ::CRYSTAL_NET::service::BookBagInfo *GetPbRawData() const;

    Int32 bookinfoitemlist_size() const;

    KERNEL_NS::SmartPtr<BookInfoItemOrmData, KERNEL_NS::AutoDelMethods::CustomDelete> &mutable_bookinfoitemlist(Int32 idx);

    void DeleteArray_bookinfoitemlist(Int32 idx, Int32 count = 1);

    const std::vector<KERNEL_NS::SmartPtr<BookInfoItemOrmData, KERNEL_NS::AutoDelMethods::CustomDelete>> &bookinfoitemlist_OrmDataArray() const;

    const ::google::protobuf::RepeatedPtrField<::CRYSTAL_NET::service::BookInfoItem> &bookinfoitemlist() const;

    const KERNEL_NS::SmartPtr<BookInfoItemOrmData, KERNEL_NS::AutoDelMethods::CustomDelete> &bookinfoitemlist_OrmDataArray(Int32 idx) const;

    const ::CRYSTAL_NET::service::BookInfoItem &bookinfoitemlist(Int32 idx) const;

    KERNEL_NS::SmartPtr<BookInfoItemOrmData, KERNEL_NS::AutoDelMethods::CustomDelete> &add_bookinfoitemlist();

    void clear_bookinfoitemlist();


protected:

    virtual bool _OnEncode(KERNEL_NS::LibStream<KERNEL_NS::_Build::MT> &stream) const override;
    virtual bool _OnEncode(KERNEL_NS::LibStream<KERNEL_NS::_Build::TL> &stream) const override;

    virtual bool _OnDecode(KERNEL_NS::LibStream<KERNEL_NS::_Build::MT> &stream) override;
    virtual bool _OnDecode(KERNEL_NS::LibStream<KERNEL_NS::_Build::TL> &stream) override;

    virtual void _AttachPb(void *pb) override;

private:

    ::CRYSTAL_NET::service::BookBagInfo *_ormRawPbData;

    std::vector<KERNEL_NS::SmartPtr<BookInfoItemOrmData, KERNEL_NS::AutoDelMethods::CustomDelete>> _bookinfoitemlist;

};

class BookBagInfoOrmDataFactory : public IOrmDataFactory
{
    POOL_CREATE_OBJ_DEFAULT_P1(IOrmDataFactory, BookBagInfoOrmDataFactory);
public:
    BookBagInfoOrmDataFactory(){}
    ~BookBagInfoOrmDataFactory(){}

    virtual void Release() override { BookBagInfoOrmDataFactory::DeleteThreadLocal_BookBagInfoOrmDataFactory(this);}

    virtual IOrmData *Create() const override;
    virtual Int64 GetOrmId() const override { return 9; }
};

SERVICE_COMMON_END
#endif // __PROTOCOLS_ORM_OUT_BOOKBAGINFOORMDATA_H__