/*!
*  MIT License
*  
*  Copyright (c) 2020 ericyonng<120453674@qq.com>
*  
*  Permission is hereby granted, free of charge, to any person obtaining a copy
*  of this software and associated documentation files (the "Software"), to deal
*  in the Software without restriction, including without limitation the rights
*  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*  copies of the Software, and to permit persons to whom the Software is
*  furnished to do so, subject to the following conditions:
*  
*  The above copyright notice and this permission notice shall be included in all
*  copies or substantial portions of the Software.
*  
*  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
*  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
*  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
*  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
*  SOFTWARE.
* 
* Author: Eric Yonng
* Description: Generated By protogentool, Dont Modify This File!!!
*/


#include "pch.h"
#include <protocols/cplusplus/library/com_library.pb.h>
#include <protocols/orm_out/BorrowBookInfoOrmData.h>

SERVICE_COMMON_BEGIN

POOL_CREATE_OBJ_DEFAULT_IMPL(BorrowBookInfoOrmData);

BorrowBookInfoOrmData::BorrowBookInfoOrmData()
:_ormRawPbData(new ::CRYSTAL_NET::service::BorrowBookInfo)
{
}

BorrowBookInfoOrmData::BorrowBookInfoOrmData(::CRYSTAL_NET::service::BorrowBookInfo *pb)
:_ormRawPbData(NULL)
{
    AttachPb(pb);
}

BorrowBookInfoOrmData::BorrowBookInfoOrmData(const BorrowBookInfoOrmData &other)
:IOrmData(reinterpret_cast<const IOrmData &>(other))
,_ormRawPbData(other._ormRawPbData ? new ::CRYSTAL_NET::service::BorrowBookInfo(*other._ormRawPbData) : NULL)
{
}

BorrowBookInfoOrmData::BorrowBookInfoOrmData(BorrowBookInfoOrmData &&other)
:IOrmData(std::forward<IOrmData>(other))
,_ormRawPbData(other._ormRawPbData)
{
    other._ormRawPbData = NULL;
}

BorrowBookInfoOrmData::BorrowBookInfoOrmData(const ::CRYSTAL_NET::service::BorrowBookInfo &pb)
:_ormRawPbData(new ::CRYSTAL_NET::service::BorrowBookInfo(pb))
{

}

BorrowBookInfoOrmData::~BorrowBookInfoOrmData()
{
    if(LIKELY(!IsAttachPb()))
        CRYSTAL_RELEASE_SAFE(_ormRawPbData);
}

void BorrowBookInfoOrmData::Release()
{
    BorrowBookInfoOrmData::DeleteThreadLocal_BorrowBookInfoOrmData(this);
}

BorrowBookInfoOrmData &BorrowBookInfoOrmData::operator =(const ::CRYSTAL_NET::service::BorrowBookInfo &pb)
{
    CRYSTAL_RELEASE_SAFE(_ormRawPbData);
    _ormRawPbData = new ::CRYSTAL_NET::service::BorrowBookInfo(pb);
    _MaskDirty(true);
    return *this;
}

BorrowBookInfoOrmData &BorrowBookInfoOrmData::operator =(const BorrowBookInfoOrmData &other)
{
    if(this == &other)
        return *this;

    IOrmData::operator =(reinterpret_cast<const IOrmData &>(other));
    CRYSTAL_RELEASE_SAFE(_ormRawPbData);
    if(other._ormRawPbData)
        _ormRawPbData = new ::CRYSTAL_NET::service::BorrowBookInfo(*other._ormRawPbData);
    if(_ormRawPbData)
    {
    }
    _MaskDirty(true);

    return *this;
}

BorrowBookInfoOrmData &BorrowBookInfoOrmData::operator =(BorrowBookInfoOrmData &&other)
{
    if(this == &other)
        return *this;

    IOrmData::operator =(std::forward<IOrmData>(other));
    _ormRawPbData = other._ormRawPbData;
    other._ormRawPbData = NULL;


    return *this;
}

void BorrowBookInfoOrmData::Clear()
{

    if(_ormRawPbData)
        _ormRawPbData->Clear();

    _MaskDirty(true);
}

void BorrowBookInfoOrmData::_AttachPb(void *pb)
{
    if(LIKELY(!IsAttachPb()))
        CRYSTAL_RELEASE_SAFE(_ormRawPbData);

    _ormRawPbData = reinterpret_cast<::CRYSTAL_NET::service::BorrowBookInfo *>(pb);


}

KERNEL_NS::LibString BorrowBookInfoOrmData::ToJsonString() const
{
    return _ormRawPbData->ToJsonString();
}

bool BorrowBookInfoOrmData::ToJsonString(std::string *data) const
{
    return _ormRawPbData->ToJsonString(data);
}

bool BorrowBookInfoOrmData::FromJsonString(const Byte8 *data, size_t len)
{
    return _ormRawPbData->FromJsonString(data, len);
}

const ::CRYSTAL_NET::service::BorrowBookInfo *BorrowBookInfoOrmData::GetPbRawData() const
{
    return _ormRawPbData;
}

void BorrowBookInfoOrmData::clear_bookid()
{
    _ormRawPbData->clear_bookid();
    _MaskDirty(true);
}

uint64_t BorrowBookInfoOrmData::bookid() const
{
    return _ormRawPbData->bookid();
}

void BorrowBookInfoOrmData::set_bookid(uint64_t value)
{
    _ormRawPbData->set_bookid(value);
    _MaskDirty(true);
}

void BorrowBookInfoOrmData::clear_isbncode()
{
    _ormRawPbData->clear_isbncode();
    _MaskDirty(true);
}

const std::string &BorrowBookInfoOrmData::isbncode() const
{
    return _ormRawPbData->isbncode();
}

void BorrowBookInfoOrmData::set_isbncode(const std::string &value)
{
    _ormRawPbData->set_isbncode(value);
    _MaskDirty(true);
}

std::string *BorrowBookInfoOrmData::mutable_isbncode()
{
    _MaskDirty(true);
    return _ormRawPbData->mutable_isbncode();
}

void BorrowBookInfoOrmData::clear_borrowcount()
{
    _ormRawPbData->clear_borrowcount();
    _MaskDirty(true);
}

int32_t BorrowBookInfoOrmData::borrowcount() const
{
    return _ormRawPbData->borrowcount();
}

void BorrowBookInfoOrmData::set_borrowcount(int32_t value)
{
    _ormRawPbData->set_borrowcount(value);
    _MaskDirty(true);
}

void BorrowBookInfoOrmData::clear_borrowtime()
{
    _ormRawPbData->clear_borrowtime();
    _MaskDirty(true);
}

int64_t BorrowBookInfoOrmData::borrowtime() const
{
    return _ormRawPbData->borrowtime();
}

void BorrowBookInfoOrmData::set_borrowtime(int64_t value)
{
    _ormRawPbData->set_borrowtime(value);
    _MaskDirty(true);
}

void BorrowBookInfoOrmData::clear_plangivebacktime()
{
    _ormRawPbData->clear_plangivebacktime();
    _MaskDirty(true);
}

int64_t BorrowBookInfoOrmData::plangivebacktime() const
{
    return _ormRawPbData->plangivebacktime();
}

void BorrowBookInfoOrmData::set_plangivebacktime(int64_t value)
{
    _ormRawPbData->set_plangivebacktime(value);
    _MaskDirty(true);
}

void BorrowBookInfoOrmData::clear_realgivebacktime()
{
    _ormRawPbData->clear_realgivebacktime();
    _MaskDirty(true);
}

int64_t BorrowBookInfoOrmData::realgivebacktime() const
{
    return _ormRawPbData->realgivebacktime();
}

void BorrowBookInfoOrmData::set_realgivebacktime(int64_t value)
{
    _ormRawPbData->set_realgivebacktime(value);
    _MaskDirty(true);
}

void BorrowBookInfoOrmData::clear_returnbackcount()
{
    _ormRawPbData->clear_returnbackcount();
    _MaskDirty(true);
}

uint64_t BorrowBookInfoOrmData::returnbackcount() const
{
    return _ormRawPbData->returnbackcount();
}

void BorrowBookInfoOrmData::set_returnbackcount(uint64_t value)
{
    _ormRawPbData->set_returnbackcount(value);
    _MaskDirty(true);
}

void BorrowBookInfoOrmData::clear_suborderid()
{
    _ormRawPbData->clear_suborderid();
    _MaskDirty(true);
}

uint64_t BorrowBookInfoOrmData::suborderid() const
{
    return _ormRawPbData->suborderid();
}

void BorrowBookInfoOrmData::set_suborderid(uint64_t value)
{
    _ormRawPbData->set_suborderid(value);
    _MaskDirty(true);
}

void BorrowBookInfoOrmData::clear_borrowdays()
{
    _ormRawPbData->clear_borrowdays();
    _MaskDirty(true);
}

int32_t BorrowBookInfoOrmData::borrowdays() const
{
    return _ormRawPbData->borrowdays();
}

void BorrowBookInfoOrmData::set_borrowdays(int32_t value)
{
    _ormRawPbData->set_borrowdays(value);
    _MaskDirty(true);
}

bool BorrowBookInfoOrmData::_OnEncode(KERNEL_NS::LibStream<KERNEL_NS::_Build::MT> &stream) const
{
    return _ormRawPbData->Encode(stream);
}

bool BorrowBookInfoOrmData::_OnEncode(KERNEL_NS::LibStream<KERNEL_NS::_Build::TL> &stream) const
{
    return _ormRawPbData->Encode(stream);
}

bool BorrowBookInfoOrmData::_OnDecode(KERNEL_NS::LibStream<KERNEL_NS::_Build::MT> &stream)
{
    return _ormRawPbData->Decode(stream);
}

bool BorrowBookInfoOrmData::_OnDecode(KERNEL_NS::LibStream<KERNEL_NS::_Build::TL> &stream)
{
    return _ormRawPbData->Decode(stream);
}

POOL_CREATE_OBJ_DEFAULT_IMPL(BorrowBookInfoOrmDataFactory);

IOrmData *BorrowBookInfoOrmDataFactory::Create() const
{
    return BorrowBookInfoOrmData::NewThreadLocal_BorrowBookInfoOrmData();
}


SERVICE_COMMON_END
