/*!
*  MIT License
*  
*  Copyright (c) 2020 ericyonng<120453674@qq.com>
*  
*  Permission is hereby granted, free of charge, to any person obtaining a copy
*  of this software and associated documentation files (the "Software"), to deal
*  in the Software without restriction, including without limitation the rights
*  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*  copies of the Software, and to permit persons to whom the Software is
*  furnished to do so, subject to the following conditions:
*  
*  The above copyright notice and this permission notice shall be included in all
*  copies or substantial portions of the Software.
*  
*  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
*  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
*  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
*  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
*  SOFTWARE.
* 
* Author: Eric Yonng
* Description: Generated By protogentool, Dont Modify This File!!!
*/


#ifndef __PROTOCOLS_ORM_OUT_ORM_ID_ENUMS_H__
#define __PROTOCOLS_ORM_OUT_ORM_ID_ENUMS_H__

#pragma once

#include <service_common/common/macro.h>

SERVICE_COMMON_BEGIN

class OrmIdEnums
{
public:
    enum ENUMS
    {
        UNKNOWN = 0,
        UserBaseInfoOrmData = 2,
        TestCustomDataOrmData = 3,
        TestOrmOrmData = 4,
        LibraryInfoOrmData = 5,
        LibararyManagerInfoOrmData = 6,
        MemberInfoOrmData = 7,
        BookInfoOrmData = 8,
        BookBagInfoOrmData = 9,
        BookInfoItemOrmData = 10,
        BorrowOrderInfoOrmData = 11,
        BorrowBookInfoOrmData = 12,
        CancelOrderReasonOrmData = 13,
        BookVariantInfoOrmData = 14,
        SnapshotClientInfoOrmData = 15,
        SimpleInfoOrmData = 16,
        MAX_ORM_ID = SimpleInfoOrmData,
    };
};

SERVICE_COMMON_END

#endif // __PROTOCOLS_ORM_OUT_ORM_ID_ENUMS_H__