/*!
*  MIT License
*  
*  Copyright (c) 2020 ericyonng<120453674@qq.com>
*  
*  Permission is hereby granted, free of charge, to any person obtaining a copy
*  of this software and associated documentation files (the "Software"), to deal
*  in the Software without restriction, including without limitation the rights
*  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*  copies of the Software, and to permit persons to whom the Software is
*  furnished to do so, subject to the following conditions:
*  
*  The above copyright notice and this permission notice shall be included in all
*  copies or substantial portions of the Software.
*  
*  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
*  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
*  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
*  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
*  SOFTWARE.
* 
* Author: Eric Yonng
* Description: Generated By protogentool, Dont Modify This File!!!
*/


#ifndef __PROTOCOLS_ORM_OUT_SIMPLEINFOORMDATA_H__
#define __PROTOCOLS_ORM_OUT_SIMPLEINFOORMDATA_H__

#pragma once
#include <kernel/kernel.h>
#include <service_common/protocol/ORM/IOrmData.h>



namespace CRYSTAL_NET {
namespace service {

class SimpleInfo;

}
}

namespace google {
    namespace protobuf {

    }
}

SERVICE_COMMON_BEGIN


SERVICE_COMMON_END

SERVICE_COMMON_BEGIN

class SimpleInfoOrmData : public SERVICE_COMMON_NS::IOrmData
{
    POOL_CREATE_OBJ_DEFAULT_P1(IOrmData, SimpleInfoOrmData)

public:
    SimpleInfoOrmData();
    SimpleInfoOrmData(::CRYSTAL_NET::service::SimpleInfo *pb);
    SimpleInfoOrmData(const SimpleInfoOrmData &other);
    SimpleInfoOrmData(SimpleInfoOrmData &&other);
    SimpleInfoOrmData(const ::CRYSTAL_NET::service::SimpleInfo &pb);
    ~SimpleInfoOrmData();

    virtual void Release() override;

    SimpleInfoOrmData &operator =(const ::CRYSTAL_NET::service::SimpleInfo &pb);

    SimpleInfoOrmData &operator =(const SimpleInfoOrmData &other);

    SimpleInfoOrmData &operator =(SimpleInfoOrmData &&other);

    virtual KERNEL_NS::LibString ToJsonString() const override;

    virtual bool ToJsonString(std::string *data) const override;

    virtual bool FromJsonString(const Byte8 *data, size_t len) override;

    virtual Int64 GetOrmId() const override{ return 16; }

    void Clear();
    const ::CRYSTAL_NET::service::SimpleInfo *GetPbRawData() const;

    void clear_maxincid();

    int64_t maxincid() const;

    void set_maxincid(int64_t value);

    void clear_dirtycount();

    int64_t dirtycount() const;

    void set_dirtycount(int64_t value);

    void clear_versionno();

    int64_t versionno() const;

    void set_versionno(int64_t value);


protected:

    virtual bool _OnEncode(KERNEL_NS::LibStream<KERNEL_NS::_Build::MT> &stream) const override;
    virtual bool _OnEncode(KERNEL_NS::LibStream<KERNEL_NS::_Build::TL> &stream) const override;

    virtual bool _OnDecode(KERNEL_NS::LibStream<KERNEL_NS::_Build::MT> &stream) override;
    virtual bool _OnDecode(KERNEL_NS::LibStream<KERNEL_NS::_Build::TL> &stream) override;

    virtual void _AttachPb(void *pb) override;

private:

    ::CRYSTAL_NET::service::SimpleInfo *_ormRawPbData;

};

class SimpleInfoOrmDataFactory : public IOrmDataFactory
{
    POOL_CREATE_OBJ_DEFAULT_P1(IOrmDataFactory, SimpleInfoOrmDataFactory);
public:
    SimpleInfoOrmDataFactory(){}
    ~SimpleInfoOrmDataFactory(){}

    virtual void Release() override { SimpleInfoOrmDataFactory::DeleteThreadLocal_SimpleInfoOrmDataFactory(this);}

    virtual IOrmData *Create() const override;
    virtual Int64 GetOrmId() const override { return 16; }
};

SERVICE_COMMON_END
#endif // __PROTOCOLS_ORM_OUT_SIMPLEINFOORMDATA_H__