/*!
*  MIT License
*  
*  Copyright (c) 2020 ericyonng<120453674@qq.com>
*  
*  Permission is hereby granted, free of charge, to any person obtaining a copy
*  of this software and associated documentation files (the "Software"), to deal
*  in the Software without restriction, including without limitation the rights
*  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*  copies of the Software, and to permit persons to whom the Software is
*  furnished to do so, subject to the following conditions:
*  
*  The above copyright notice and this permission notice shall be included in all
*  copies or substantial portions of the Software.
*  
*  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
*  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
*  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
*  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
*  SOFTWARE.
* 
* Author: Eric Yonng
* Description: Generated By protogentool, Dont Modify This File!!!
*/


#ifndef __PROTOCOLS_ORM_OUT_USERLOGININFOORMDATA_H__
#define __PROTOCOLS_ORM_OUT_USERLOGININFOORMDATA_H__

#pragma once
#include <kernel/kernel.h>
#include <service_common/protocol/ORM/IOrmData.h>

#include <string>


namespace CRYSTAL_NET {
namespace service {

class UserLoginInfo;

}
}

namespace google {
    namespace protobuf {

    }
}

SERVICE_COMMON_BEGIN


SERVICE_COMMON_END

SERVICE_COMMON_BEGIN

class UserLoginInfoOrmData : public SERVICE_COMMON_NS::IOrmData
{
    POOL_CREATE_OBJ_DEFAULT_P1(IOrmData, UserLoginInfoOrmData)

public:
    UserLoginInfoOrmData();
    UserLoginInfoOrmData(::CRYSTAL_NET::service::UserLoginInfo *pb);
    UserLoginInfoOrmData(const UserLoginInfoOrmData &other);
    UserLoginInfoOrmData(UserLoginInfoOrmData &&other);
    UserLoginInfoOrmData(const ::CRYSTAL_NET::service::UserLoginInfo &pb);
    ~UserLoginInfoOrmData();

    virtual void Release() override;

    UserLoginInfoOrmData &operator =(const ::CRYSTAL_NET::service::UserLoginInfo &pb);

    UserLoginInfoOrmData &operator =(const UserLoginInfoOrmData &other);

    UserLoginInfoOrmData &operator =(UserLoginInfoOrmData &&other);

    virtual KERNEL_NS::LibString ToJsonString() const override;

    virtual bool ToJsonString(std::string *data) const override;

    virtual bool FromJsonString(const Byte8 *data, size_t len) override;

    virtual Int64 GetOrmId() const override{ return 18; }

    void Clear();
    const ::CRYSTAL_NET::service::UserLoginInfo *GetPbRawData() const;

    void clear_token();

    const std::string &token() const;

    void set_token(const std::string &value);

    std::string *mutable_token();

    void clear_key();

    const std::string &key() const;

    void set_key(const std::string &value);

    std::string *mutable_key();

    void clear_keyexpiretime();

    int64_t keyexpiretime() const;

    void set_keyexpiretime(int64_t value);


protected:

    virtual bool _OnEncode(KERNEL_NS::LibStream<KERNEL_NS::_Build::MT> &stream) const override;
    virtual bool _OnEncode(KERNEL_NS::LibStream<KERNEL_NS::_Build::TL> &stream) const override;

    virtual bool _OnDecode(KERNEL_NS::LibStream<KERNEL_NS::_Build::MT> &stream) override;
    virtual bool _OnDecode(KERNEL_NS::LibStream<KERNEL_NS::_Build::TL> &stream) override;

    virtual void _AttachPb(void *pb) override;

private:

    ::CRYSTAL_NET::service::UserLoginInfo *_ormRawPbData;

};

class UserLoginInfoOrmDataFactory : public IOrmDataFactory
{
    POOL_CREATE_OBJ_DEFAULT_P1(IOrmDataFactory, UserLoginInfoOrmDataFactory);
public:
    UserLoginInfoOrmDataFactory(){}
    ~UserLoginInfoOrmDataFactory(){}

    virtual void Release() override { UserLoginInfoOrmDataFactory::DeleteThreadLocal_UserLoginInfoOrmDataFactory(this);}

    virtual IOrmData *Create() const override;
    virtual Int64 GetOrmId() const override { return 18; }
};

SERVICE_COMMON_END
#endif // __PROTOCOLS_ORM_OUT_USERLOGININFOORMDATA_H__