/*!
 * MIT License
 *  
 * Copyright (c) 2020 Eric Yonng<120453674@qq.com>
 *  
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *  
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *  
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *  
 * 
 * Date: 2024-05-11 14:51:29
 * Author: Eric Yonng
 * Description: 
*/


#pragma once

#include <kernel/kernel.h>

// app配置
static const KERNEL_NS::LibString s_appIniContent = 
"[KERNEL_OPTION]\n"
"\n"
"    BlackWhiteListMode=14\n"
"\n"
"    MaxSessionQuantity=100000\n"
"\n"
"    LinkInOutPollerAmount = 0\n"
"\n"
"    DataTransferPollerAmount = 0\n"
"\n"
"    MaxRecvBytesPerFrame = 16384\n"
"\n"
"    MaxSendBytesPerFrame = 16384\n"
"\n"
"    MaxAcceptCountPerFrame = 1024\n"
"\n"
"    MaxPieceTimeInMicroSecPerFrame = 8000\n"
"\n"
"    MaxPollerScanMilliseconds = 1\n"
"\n"
"    MaxPollerMsgPriorityLevel = 3\n"
"\n"
"    PollerMonitorEventPriorityLevel = -1\n"
"\n"
"    PriorityLevelDefine = 0,INNER|1,DB|2,OUTER1|3,OUTER2\n"
"\n"
"    SessionBufferCapicity = 8192\n"
"\n"
"\n"
"    SessionRecvPacketSpeedLimit = 1000\n"
"\n"
"\n"
"    SessionRecvPacketSpeedTimeUnitMs = 1\n"
"\n"
"\n"
"    SessionRecvPacketStackLimit = 100\n"
"\n"
"\n"
"[ServiceCommon]\n"
"\n"
"    ActiveServiceItem = ConfigExporter\n"
"\n"
"[ApplicationConfig]\n"
"\n"
"    AliasName = ConfigExporter\n"
"\n"
"    ProjectMainServiceName = ConfigExporter\n"
"\n"
"    MachineId = 0\n"
"\n"
"    RegisterTime = 0\n"
"\n"
"    RegisterPath = \n"
"\n"
"    RegisterProcessId = 0\n"
"\n"
"    MachineApplyId = \n"
"\n"
"[ConfigExporter]\n"
"    MaxPieceTimeInMicroseconds = 8000\n"
"\n"
"    PollerMaxSleepMilliseconds = 20\n"
"\n"
"    FrameUpdateTimeMs = 50\n"
"\n"
"    PORT_SESSION_TYPE = 3900,OUTER|3901,INNER\n"
;

// 日志配置表
static const KERNEL_NS::LibString s_logIniContent = 
"[Common]\n"
"FileName=0,,1|1,Crash,2|2,Net,3|3,Custom,1|4,Sys,2|5,MemMonitor,2|6,Trace,2|7,Monitor,4\n"
"ExtName=.log\n"
"MaxLogCacheMB=16\n"
"LogTimerIntervalMs=1000\n"
"MaxFileSizeMB=256\n"
"IsEnableLog=1\n"
"LogPath=1,\n"
"\n"
"[LogLevel]\n"
"\nDebug           = 1,0,1,White|Black,1,0,0,1\n"
"\nInfo            = 1,0,1,White|Black,2,0,0,1\n"
"\nWarn            = 1,0,1,LightYellow|Black,3,0,0,1\n"
"\nError           = 1,0,1,Red|Black,4,0,1,1\n"
"\nCrash           = 1,1,1,Red|Black,5,0,0,1\n"
"\nNet             = 1,2,0,White|Black,6,0,0,0\n"
"\nNetDebug        = 1,2,0,White|Black,7,0,0,0\n"
"\nNetInfo         = 1,2,0,White|Black,8,0,0,0\n"
"\nNetWarn         = 1,2,1,LightYellow|Black,9,0,0,0\n"
"\nNetError        = 1,2,1,Red|Black,10,0,1,0\n"
"\nNetTrace        = 1,2,0,Green|Black,11,1,0,0\n"
"\nCustom          = 1,3,1,White|Black,12,0,0,1\n"
"\nSys    			= 1,4,0,White|Black,13,0,0,1\n"
"\nMemMonitor    	= 1,5,0,White|Black,14,0,0,0\n"
"\nTrace           = 1,6,0,Green|Black,15,1,0,1\n"
"\nMonitorInfo     = 1,7,1,Green|Black,16,1,0,0\n"
;

// 控制台配置表
static const KERNEL_NS::LibString s_consoleIniContent = 
"[Win32FrontConsoleColor]\n"
"Black        = 0\n"
"Red          = 4\n"
"Green        = 2\n"
"Blue         = 1\n"
"Yellow       = 6\n"
"Purple       = 5\n"
"Cyan         = 3\n"
"White        = 7\n"
"Gray         = 8\n"
"LightYellow  = 14\n"
"Highlight    = 8\n"
"FrontDefault = 7\n"
"\n"
"[Win32BackConsoleColor]\n"
"Black       = 0  \n"
"Red         = 64 \n"
"Green       = 32 \n"
"Blue        = 16 \n"
"Yellow      = 96 \n"
"Purple      = 80 \n"
"Cyan        = 48 \n"
"White       = 112\n"
"Highlight   = 128\n"
"BackDefault = 0  \n"
;


static const KERNEL_NS::LibString s_LogYamlContent = \
"# Author: EricYonng(120453674@qq.com)\n"
"# Date:2026.01.29\n"
"# Desc:日志配置\n"
"\n"
"LogCfg:\n"
"  LogCommon:\n"
"    # 日志文件配置\n"
"    LogFileDefineList:\n"
"      # 线程关联性id:1:业务逻辑日志线程, 2:系统日志线程(包括监控等),3:网络日志线程\n"
"      # 主逻辑日志文件\n"
"      - FileId: 0\n"
"        FileName: \n"
"        # 线程相关性id, 相同id的多个文件会绑定在同一个线程\n"
"        ThreadRelationshipId: 1\n"
"\n"
"        # crash日志\n"
"      - FileId: 1\n"
"        FileName: Crash\n"
"        ThreadRelationshipId: 1\n"
"\n"
"        # 网络日志\n"
"      - FileId: 2\n"
"        FileName: Net\n"
"        ThreadRelationshipId: 3\n"
"\n"
"        # Custom日志\n"
"      - FileId: 3\n"
"        FileName: Custom\n"
"        ThreadRelationshipId: 1\n"
"\n"
"        # 系统日志\n"
"      - FileId: 4\n"
"        FileName: Sys\n"
"        ThreadRelationshipId: 2\n"
"\n"
"        # 内存监控日志\n"
"      - FileId: 5\n"
"        FileName: MemMonitor\n"
"        ThreadRelationshipId: 2\n"
"\n"
"        # 跟踪日志\n"
"      - FileId: 6\n"
"        FileName: Trace\n"
"        ThreadRelationshipId: 1\n"
"\n"
"        # 监控日志\n"
"      - FileId: 7\n"
"        FileName: Monitor\n"
"        ThreadRelationshipId: 2\n"
"\n"
"        # db日志\n"
"      - FileId: 8\n"
"        FileName: DB\n"
"        ThreadRelationshipId: 2\n"
"\n"
"    # 文件后缀\n"
"    ExtName: .log\n"
"    # 日志最大缓存限制,超过则即时着盘\n"
"    MaxLogCacheMB: 16\n"
"    # 日志着盘时间间隔,定时着盘 格式:00:00:01.xxx, xxx部分是纳秒\n"
"    LogTimerInterval: 00:00:01\n"
"    # 日志单文件最大大小,超过会创建分立文件\n"
"    MaxFileSizeMB: 256\n"
"    # 是否产出日志\n"
"    IsEnableLog: 1\n"
"    # 日志路径:[是否使用程序名当日志的一级目录][路径]\n"
"    LogPath:\n"
"      IsUseProgramNameAsFirstLevelPath: 1\n"
"      # 路径:\n"
"      # 若使用程序名当一级目录则可以缺省指定路径名 若此时有指定路径名,程序名路径会追加在该指定路径成为二级目录\n"
"      # 若指定了绝对路径则必定使用给定的绝对路径 若此时又指定了程序名当目录 程序名路径追加在该指定路径成为二级目录\n"
"      PartPath: \n"
"\n"
"  # 日志等级配置\n"
"  LogLevelList:\n"
"    # Debug 配置\n"
"    - Enable: 1\n"
"      # 文件id\n"
"      FileId: 0\n"
"      # 级别名\n"
"      LevelName: Debug\n"
"      # 是否输出到控制台\n"
"      EnableConsole: 1\n"
"      # 前景色\n"
"      FgColor: White\n"
"      # 背景色\n"
"      BgColor: Black\n"
"      # 日志等级id\n"
"      LevelId: 1\n"
"      # 是否实时输出\n"
"      EnableRealTime: 0\n"
"      # 是否打印堆栈\n"
"      PRINT_STACK_TRACE_BACK: 0\n"
"      # 是否落盘\n"
"      NEED_WRITE_FILE: 0\n"
"\n"
"    # Info 配置\n"
"    - Enable: 1\n"
"      # 级别名\n"
"      LevelName: Info\n"
"      # 文件id\n"
"      FileId: 0\n"
"      # 是否输出到控制台\n"
"      EnableConsole: 1\n"
"      # 前景色\n"
"      FgColor: White\n"
"      # 背景色\n"
"      BgColor: Black\n"
"      # 日志等级id\n"
"      LevelId: 2\n"
"      # 是否实时输出\n"
"      EnableRealTime: 0\n"
"      # 是否打印堆栈\n"
"      PRINT_STACK_TRACE_BACK: 0\n"
"      # 是否落盘\n"
"      NEED_WRITE_FILE: 0\n"
"\n"
"    # Warn 配置\n"
"    - Enable: 1\n"
"      # 级别名\n"
"      LevelName: Warn\n"
"      # 文件id\n"
"      FileId: 0\n"
"      # 是否输出到控制台\n"
"      EnableConsole: 1\n"
"      # 前景色\n"
"      FgColor: LightYellow\n"
"      # 背景色\n"
"      BgColor: Black\n"
"      # 日志等级id\n"
"      LevelId: 3\n"
"      # 是否实时输出\n"
"      EnableRealTime: 0\n"
"      # 是否打印堆栈\n"
"      PRINT_STACK_TRACE_BACK: 0\n"
"      # 是否落盘\n"
"      NEED_WRITE_FILE: 0\n"
"\n"
"    # Error 配置\n"
"    - Enable: 1\n"
"      # 级别名\n"
"      LevelName: Error\n"
"      # 文件id\n"
"      FileId: 0\n"
"      # 是否输出到控制台\n"
"      EnableConsole: 1\n"
"      # 前景色\n"
"      FgColor: Red\n"
"      # 背景色\n"
"      BgColor: Black\n"
"      # 日志等级id\n"
"      LevelId: 4\n"
"      # 是否实时输出\n"
"      EnableRealTime: 0\n"
"      # 是否打印堆栈\n"
"      PRINT_STACK_TRACE_BACK: 1\n"
"      # 是否落盘\n"
"      NEED_WRITE_FILE: 0\n"
"\n"
"    # Crash 配置\n"
"    - Enable: 1\n"
"      # 级别名\n"
"      LevelName: Crash\n"
"      # 文件id\n"
"      FileId: 1\n"
"      # 是否输出到控制台\n"
"      EnableConsole: 1\n"
"      # 前景色\n"
"      FgColor: Red\n"
"      # 背景色\n"
"      BgColor: Black\n"
"      # 日志等级id\n"
"      LevelId: 5\n"
"      # 是否实时输出\n"
"      EnableRealTime: 0\n"
"      # 是否打印堆栈\n"
"      PRINT_STACK_TRACE_BACK: 0\n"
"      # 是否落盘\n"
"      NEED_WRITE_FILE: 0\n"
"\n"
"    # Net 配置\n"
"    - Enable: 1\n"
"      # 级别名\n"
"      LevelName: Net\n"
"      # 文件id\n"
"      FileId: 2\n"
"      # 是否输出到控制台\n"
"      EnableConsole: 0\n"
"      # 前景色\n"
"      FgColor: White\n"
"      # 背景色\n"
"      BgColor: Black\n"
"      # 日志等级id\n"
"      LevelId: 6\n"
"      # 是否实时输出\n"
"      EnableRealTime: 0\n"
"      # 是否打印堆栈\n"
"      PRINT_STACK_TRACE_BACK: 0\n"
"      # 是否落盘\n"
"      NEED_WRITE_FILE: 0\n"
"\n"
"    # NetDebug 配置\n"
"    - Enable: 1\n"
"      # 级别名\n"
"      LevelName: NetDebug\n"
"      # 文件id\n"
"      FileId: 2\n"
"      # 是否输出到控制台\n"
"      EnableConsole: 0\n"
"      # 前景色\n"
"      FgColor: White\n"
"      # 背景色\n"
"      BgColor: Black\n"
"      # 日志等级id\n"
"      LevelId: 7\n"
"      # 是否实时输出\n"
"      EnableRealTime: 0\n"
"      # 是否打印堆栈\n"
"      PRINT_STACK_TRACE_BACK: 0\n"
"      # 是否落盘\n"
"      NEED_WRITE_FILE: 0\n"
"\n"
"    # NetInfo 配置\n"
"    - Enable: 1\n"
"      # 级别名\n"
"      LevelName: NetInfo\n"
"      # 文件id\n"
"      FileId: 2\n"
"      # 是否输出到控制台\n"
"      EnableConsole: 0\n"
"      # 前景色\n"
"      FgColor: White\n"
"      # 背景色\n"
"      BgColor: Black\n"
"      # 日志等级id\n"
"      LevelId: 8\n"
"      # 是否实时输出\n"
"      EnableRealTime: 0\n"
"      # 是否打印堆栈\n"
"      PRINT_STACK_TRACE_BACK: 0\n"
"      # 是否落盘\n"
"      NEED_WRITE_FILE: 0\n"
"\n"
"    # NetWarn 配置\n"
"    - Enable: 1\n"
"      # 级别名\n"
"      LevelName: NetWarn\n"
"      # 文件id\n"
"      FileId: 2\n"
"      # 是否输出到控制台\n"
"      EnableConsole: 1\n"
"      # 前景色\n"
"      FgColor: LightYellow\n"
"      # 背景色\n"
"      BgColor: Black\n"
"      # 日志等级id\n"
"      LevelId: 9\n"
"      # 是否实时输出\n"
"      EnableRealTime: 0\n"
"      # 是否打印堆栈\n"
"      PRINT_STACK_TRACE_BACK: 0\n"
"      # 是否落盘\n"
"      NEED_WRITE_FILE: 0\n"
"\n"
"    # NetError 配置\n"
"    - Enable: 1\n"
"      # 级别名\n"
"      LevelName: NetError\n"
"      # 文件id\n"
"      FileId: 2\n"
"      # 是否输出到控制台\n"
"      EnableConsole: 1\n"
"      # 前景色\n"
"      FgColor: Red\n"
"      # 背景色\n"
"      BgColor: Black\n"
"      # 日志等级id\n"
"      LevelId: 10\n"
"      # 是否实时输出\n"
"      EnableRealTime: 0\n"
"      # 是否打印堆栈\n"
"      PRINT_STACK_TRACE_BACK: 1\n"
"      # 是否落盘\n"
"      NEED_WRITE_FILE: 0\n"
"\n"
"    # NetTrace 配置\n"
"    - Enable: 1\n"
"      # 级别名\n"
"      LevelName: NetTrace\n"
"      # 文件id\n"
"      FileId: 2\n"
"      # 是否输出到控制台\n"
"      EnableConsole: 0\n"
"      # 前景色\n"
"      FgColor: Green\n"
"      # 背景色\n"
"      BgColor: Black\n"
"      # 日志等级id\n"
"      LevelId: 11\n"
"      # 是否实时输出\n"
"      EnableRealTime: 1\n"
"      # 是否打印堆栈\n"
"      PRINT_STACK_TRACE_BACK: 0\n"
"      # 是否落盘\n"
"      NEED_WRITE_FILE: 0\n"
"\n"
"    # Custom 配置\n"
"    - Enable: 1\n"
"      # 级别名\n"
"      LevelName: Custom\n"
"      # 文件id\n"
"      FileId: 3\n"
"      # 是否输出到控制台\n"
"      EnableConsole: 1\n"
"      # 前景色\n"
"      FgColor: White\n"
"      # 背景色\n"
"      BgColor: Black\n"
"      # 日志等级id\n"
"      LevelId: 12\n"
"      # 是否实时输出\n"
"      EnableRealTime: 0\n"
"      # 是否打印堆栈\n"
"      PRINT_STACK_TRACE_BACK: 0\n"
"      # 是否落盘\n"
"      NEED_WRITE_FILE: 0\n"
"\n"
"    # Sys 配置\n"
"    - Enable: 1\n"
"      # 级别名\n"
"      LevelName: Sys\n"
"      # 文件id\n"
"      FileId: 4\n"
"      # 是否输出到控制台\n"
"      EnableConsole: 0\n"
"      # 前景色\n"
"      FgColor: White\n"
"      # 背景色\n"
"      BgColor: Black\n"
"      # 日志等级id\n"
"      LevelId: 13\n"
"      # 是否实时输出\n"
"      EnableRealTime: 0\n"
"      # 是否打印堆栈\n"
"      PRINT_STACK_TRACE_BACK: 0\n"
"      # 是否落盘\n"
"      NEED_WRITE_FILE: 0\n"
"\n"
"    # MemMonitor 配置\n"
"    - Enable: 1\n"
"      # 级别名\n"
"      LevelName: MemMonitor\n"
"      # 文件id\n"
"      FileId: 5\n"
"      # 是否输出到控制台\n"
"      EnableConsole: 1\n"
"      # 前景色\n"
"      FgColor: White\n"
"      # 背景色\n"
"      BgColor: Black\n"
"      # 日志等级id\n"
"      LevelId: 14\n"
"      # 是否实时输出\n"
"      EnableRealTime: 0\n"
"      # 是否打印堆栈\n"
"      PRINT_STACK_TRACE_BACK: 0\n"
"      # 是否落盘\n"
"      NEED_WRITE_FILE: 0\n"
"\n"
"    # Trace 配置\n"
"    - Enable: 1\n"
"      # 级别名\n"
"      LevelName: Trace\n"
"      # 文件id\n"
"      FileId: 6\n"
"      # 是否输出到控制台\n"
"      EnableConsole: 0\n"
"      # 前景色\n"
"      FgColor: Green\n"
"      # 背景色\n"
"      BgColor: Black\n"
"      # 日志等级id\n"
"      LevelId: 15\n"
"      # 是否实时输出\n"
"      EnableRealTime: 1\n"
"      # 是否打印堆栈\n"
"      PRINT_STACK_TRACE_BACK: 0\n"
"      # 是否落盘\n"
"      NEED_WRITE_FILE: 0\n"
"\n"
"    # MonitorInfo 配置\n"
"    - Enable: 1\n"
"      # 级别名\n"
"      LevelName: MonitorInfo\n"
"      # 文件id\n"
"      FileId: 7\n"
"      # 是否输出到控制台\n"
"      EnableConsole: 1\n"
"      # 前景色\n"
"      FgColor: Green\n"
"      # 背景色\n"
"      BgColor: Black\n"
"      # 日志等级id\n"
"      LevelId: 16\n"
"      # 是否实时输出\n"
"      EnableRealTime: 1\n"
"      # 是否打印堆栈\n"
"      PRINT_STACK_TRACE_BACK: 0\n"
"      # 是否落盘\n"
"      NEED_WRITE_FILE: 0\n"
"\n"
"    # FailSql 配置\n"
"    - Enable: 1\n"
"      # 级别名\n"
"      LevelName: FailSql\n"
"      # 文件id\n"
"      FileId: 8\n"
"      # 是否输出到控制台\n"
"      EnableConsole: 0\n"
"      # 前景色\n"
"      FgColor: LightYellow\n"
"      # 背景色\n"
"      BgColor: Black\n"
"      # 日志等级id\n"
"      LevelId: 17\n"
"      # 是否实时输出\n"
"      EnableRealTime: 1\n"
"      # 是否打印堆栈\n"
"      PRINT_STACK_TRACE_BACK: 0\n"
"      # 是否落盘\n"
"      NEED_WRITE_FILE: 0\n"
"\n"
"    # DumpSql 配置\n"
"    - Enable: 1\n"
"      # 级别名\n"
"      LevelName: DumpSql\n"
"      # 文件id\n"
"      FileId: 8\n"
"      # 是否输出到控制台\n"
"      EnableConsole: 0\n"
"      # 前景色\n"
"      FgColor: White\n"
"      # 背景色\n"
"      BgColor: Black\n"
"      # 日志等级id\n"
"      LevelId: 18\n"
"      # 是否实时输出\n"
"      EnableRealTime: 1\n"
"      # 是否打印堆栈\n"
"      PRINT_STACK_TRACE_BACK: 0\n"
"      # 是否落盘\n"
"      NEED_WRITE_FILE: 0\n"
;