/*!
*  MIT License
*  
*  Copyright (c) 2020 ericyonng<120453674@qq.com>
*  
*  Permission is hereby granted, free of charge, to any person obtaining a copy
*  of this software and associated documentation files (the "Software"), to deal
*  in the Software without restriction, including without limitation the rights
*  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*  copies of the Software, and to permit persons to whom the Software is
*  furnished to do so, subject to the following conditions:
*  
*  The above copyright notice and this permission notice shall be included in all
*  copies or substantial portions of the Software.
*  
*  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
*  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
*  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
*  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
*  SOFTWARE.
* 
* Author: Eric Yonng
* Description: Generated By protogentool, Dont Modify This File!!!
*/


#include "pch.h"
#include <protocols/cplusplus/library/com_library.pb.h>
#include <protocols/orm_out/CancelOrderReasonOrmData.h>

SERVICE_COMMON_BEGIN

CancelOrderReasonOrmData::CancelOrderReasonOrmData()
:_ormRawPbData(new ::CRYSTAL_NET::service::CancelOrderReason)
{
}

CancelOrderReasonOrmData::CancelOrderReasonOrmData(::CRYSTAL_NET::service::CancelOrderReason *pb)
:_ormRawPbData(NULL)
{
    AttachPb(pb);
}

CancelOrderReasonOrmData::CancelOrderReasonOrmData(const CancelOrderReasonOrmData &other)
:IOrmData(reinterpret_cast<const IOrmData &>(other))
,_ormRawPbData(other._ormRawPbData ? new ::CRYSTAL_NET::service::CancelOrderReason(*other._ormRawPbData) : NULL)
{
    SetAttachPbFlag(false);
}

CancelOrderReasonOrmData::CancelOrderReasonOrmData(CancelOrderReasonOrmData &&other)
:IOrmData(std::forward<IOrmData>(other))
,_ormRawPbData(other._ormRawPbData)
{
    other._ormRawPbData = NULL;
}

CancelOrderReasonOrmData::CancelOrderReasonOrmData(const ::CRYSTAL_NET::service::CancelOrderReason &pb)
:_ormRawPbData(new ::CRYSTAL_NET::service::CancelOrderReason(pb))
{

}

CancelOrderReasonOrmData::~CancelOrderReasonOrmData()
{
    if(LIKELY(!IsAttachPb()))
        CRYSTAL_RELEASE_SAFE(_ormRawPbData);
}

void CancelOrderReasonOrmData::Release()
{
    CancelOrderReasonOrmData::DeleteThreadLocal_CancelOrderReasonOrmData(this);
}

CancelOrderReasonOrmData &CancelOrderReasonOrmData::operator =(const ::CRYSTAL_NET::service::CancelOrderReason &pb)
{
    if(LIKELY(!IsAttachPb()))
        CRYSTAL_RELEASE_SAFE(_ormRawPbData);

    SetAttachPbFlag(false);
    _ormRawPbData = new ::CRYSTAL_NET::service::CancelOrderReason(pb);
    _MaskDirty(true);
    return *this;
}

CancelOrderReasonOrmData &CancelOrderReasonOrmData::operator =(const CancelOrderReasonOrmData &other)
{
    if(this == &other)
        return *this;

    IOrmData::operator =(reinterpret_cast<const IOrmData &>(other));
    if(LIKELY(!IsAttachPb()))
        CRYSTAL_RELEASE_SAFE(_ormRawPbData);

    _ormRawPbData = NULL;
    SetAttachPbFlag(false);
    if(other._ormRawPbData)
        _ormRawPbData = new ::CRYSTAL_NET::service::CancelOrderReason(*other._ormRawPbData);
    _MaskDirty(true);

    return *this;
}

CancelOrderReasonOrmData &CancelOrderReasonOrmData::operator =(CancelOrderReasonOrmData &&other)
{
    if(this == &other)
        return *this;

    IOrmData::operator =(std::forward<IOrmData>(other));
    _ormRawPbData = other._ormRawPbData;
    other._ormRawPbData = NULL;


    return *this;
}

void CancelOrderReasonOrmData::Clear()
{

    if(_ormRawPbData)
        _ormRawPbData->Clear();

    _MaskDirty(true);
}

void CancelOrderReasonOrmData::_AttachPb(void *pb)
{
    if(LIKELY(!IsAttachPb()))
        CRYSTAL_RELEASE_SAFE(_ormRawPbData);

    _ormRawPbData = reinterpret_cast<::CRYSTAL_NET::service::CancelOrderReason *>(pb);


}

KERNEL_NS::LibString CancelOrderReasonOrmData::ToJsonString() const
{
    return _ormRawPbData->ToJsonString();
}

bool CancelOrderReasonOrmData::ToJsonString(std::string *data) const
{
    return _ormRawPbData->ToJsonString(data);
}

bool CancelOrderReasonOrmData::FromJsonString(const Byte8 *data, size_t len)
{
    return _ormRawPbData->FromJsonString(data, len);
}

const ::CRYSTAL_NET::service::CancelOrderReason *CancelOrderReasonOrmData::GetPbRawData() const
{
    return _ormRawPbData;
}

void CancelOrderReasonOrmData::clear_cancelreason()
{
    _ormRawPbData->clear_cancelreason();
    _MaskDirty(true);
}

int32_t CancelOrderReasonOrmData::cancelreason() const
{
    return _ormRawPbData->cancelreason();
}

void CancelOrderReasonOrmData::set_cancelreason(int32_t value)
{
    _ormRawPbData->set_cancelreason(value);
    _MaskDirty(true);
}

void CancelOrderReasonOrmData::clear_cancelinfo()
{
    _ormRawPbData->clear_cancelinfo();
    _MaskDirty(true);
}

const std::string &CancelOrderReasonOrmData::cancelinfo() const
{
    return _ormRawPbData->cancelinfo();
}

void CancelOrderReasonOrmData::set_cancelinfo(const std::string &value)
{
    _ormRawPbData->set_cancelinfo(value);
    _MaskDirty(true);
}

std::string *CancelOrderReasonOrmData::mutable_cancelinfo()
{
    _MaskDirty(true);
    return _ormRawPbData->mutable_cancelinfo();
}

bool CancelOrderReasonOrmData::_OnEncode(KERNEL_NS::LibStream<KERNEL_NS::_Build::MT> &stream) const
{
    return _ormRawPbData->Encode(stream);
}

bool CancelOrderReasonOrmData::_OnEncode(KERNEL_NS::LibStream<KERNEL_NS::_Build::TL> &stream) const
{
    return _ormRawPbData->Encode(stream);
}

bool CancelOrderReasonOrmData::_OnDecode(KERNEL_NS::LibStream<KERNEL_NS::_Build::MT> &stream)
{
    return _ormRawPbData->Decode(stream);
}

bool CancelOrderReasonOrmData::_OnDecode(KERNEL_NS::LibStream<KERNEL_NS::_Build::TL> &stream)
{
    return _ormRawPbData->Decode(stream);
}

IOrmData *CancelOrderReasonOrmDataFactory::Create() const
{
    return CancelOrderReasonOrmData::NewThreadLocal_CancelOrderReasonOrmData();
}


SERVICE_COMMON_END
