/*!
*  MIT License
*  
*  Copyright (c) 2020 ericyonng<120453674@qq.com>
*  
*  Permission is hereby granted, free of charge, to any person obtaining a copy
*  of this software and associated documentation files (the "Software"), to deal
*  in the Software without restriction, including without limitation the rights
*  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*  copies of the Software, and to permit persons to whom the Software is
*  furnished to do so, subject to the following conditions:
*  
*  The above copyright notice and this permission notice shall be included in all
*  copies or substantial portions of the Software.
*  
*  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
*  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
*  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
*  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
*  SOFTWARE.
* 
* Author: Eric Yonng
* Description: Generated By protogentool, Dont Modify This File!!!
*/


#include "pch.h"
#include <protocols/cplusplus/comp_test.pb.h>
#include <protocols/orm_out/TestMgrDataOrmData.h>

SERVICE_COMMON_BEGIN

TestMgrDataOrmData::TestMgrDataOrmData()
:_ormRawPbData(new ::CRYSTAL_NET::service::TestMgrData)
{
}

TestMgrDataOrmData::TestMgrDataOrmData(::CRYSTAL_NET::service::TestMgrData *pb)
:_ormRawPbData(NULL)
{
    AttachPb(pb);
}

TestMgrDataOrmData::TestMgrDataOrmData(const TestMgrDataOrmData &other)
:IOrmData(reinterpret_cast<const IOrmData &>(other))
,_ormRawPbData(other._ormRawPbData ? new ::CRYSTAL_NET::service::TestMgrData(*other._ormRawPbData) : NULL)
{
    SetAttachPbFlag(false);
}

TestMgrDataOrmData::TestMgrDataOrmData(TestMgrDataOrmData &&other)
:IOrmData(std::forward<IOrmData>(other))
,_ormRawPbData(other._ormRawPbData)
{
    other._ormRawPbData = NULL;
}

TestMgrDataOrmData::TestMgrDataOrmData(const ::CRYSTAL_NET::service::TestMgrData &pb)
:_ormRawPbData(new ::CRYSTAL_NET::service::TestMgrData(pb))
{

}

TestMgrDataOrmData::~TestMgrDataOrmData()
{
    if(LIKELY(!IsAttachPb()))
        CRYSTAL_RELEASE_SAFE(_ormRawPbData);
}

void TestMgrDataOrmData::Release()
{
    TestMgrDataOrmData::DeleteThreadLocal_TestMgrDataOrmData(this);
}

TestMgrDataOrmData &TestMgrDataOrmData::operator =(const ::CRYSTAL_NET::service::TestMgrData &pb)
{
    if(LIKELY(!IsAttachPb()))
        CRYSTAL_RELEASE_SAFE(_ormRawPbData);

    SetAttachPbFlag(false);
    _ormRawPbData = new ::CRYSTAL_NET::service::TestMgrData(pb);
    _MaskDirty(true);
    return *this;
}

TestMgrDataOrmData &TestMgrDataOrmData::operator =(const TestMgrDataOrmData &other)
{
    if(this == &other)
        return *this;

    IOrmData::operator =(reinterpret_cast<const IOrmData &>(other));
    if(LIKELY(!IsAttachPb()))
        CRYSTAL_RELEASE_SAFE(_ormRawPbData);

    _ormRawPbData = NULL;
    SetAttachPbFlag(false);
    if(other._ormRawPbData)
        _ormRawPbData = new ::CRYSTAL_NET::service::TestMgrData(*other._ormRawPbData);
    _MaskDirty(true);

    return *this;
}

TestMgrDataOrmData &TestMgrDataOrmData::operator =(TestMgrDataOrmData &&other)
{
    if(this == &other)
        return *this;

    IOrmData::operator =(std::forward<IOrmData>(other));
    _ormRawPbData = other._ormRawPbData;
    other._ormRawPbData = NULL;


    return *this;
}

void TestMgrDataOrmData::Clear()
{

    if(_ormRawPbData)
        _ormRawPbData->Clear();

    _MaskDirty(true);
}

void TestMgrDataOrmData::_AttachPb(void *pb)
{
    if(LIKELY(!IsAttachPb()))
        CRYSTAL_RELEASE_SAFE(_ormRawPbData);

    _ormRawPbData = reinterpret_cast<::CRYSTAL_NET::service::TestMgrData *>(pb);


}

KERNEL_NS::LibString TestMgrDataOrmData::ToJsonString() const
{
    return _ormRawPbData->ToJsonString();
}

bool TestMgrDataOrmData::ToJsonString(std::string *data) const
{
    return _ormRawPbData->ToJsonString(data);
}

bool TestMgrDataOrmData::FromJsonString(const Byte8 *data, size_t len)
{
    return _ormRawPbData->FromJsonString(data, len);
}

const ::CRYSTAL_NET::service::TestMgrData *TestMgrDataOrmData::GetPbRawData() const
{
    return _ormRawPbData;
}

void TestMgrDataOrmData::clear_account()
{
    _ormRawPbData->clear_account();
    _MaskDirty(true);
}

const std::string &TestMgrDataOrmData::account() const
{
    return _ormRawPbData->account();
}

void TestMgrDataOrmData::set_account(const std::string &value)
{
    _ormRawPbData->set_account(value);
    _MaskDirty(true);
}

std::string *TestMgrDataOrmData::mutable_account()
{
    _MaskDirty(true);
    return _ormRawPbData->mutable_account();
}

void TestMgrDataOrmData::clear_testid()
{
    _ormRawPbData->clear_testid();
    _MaskDirty(true);
}

int64_t TestMgrDataOrmData::testid() const
{
    return _ormRawPbData->testid();
}

void TestMgrDataOrmData::set_testid(int64_t value)
{
    _ormRawPbData->set_testid(value);
    _MaskDirty(true);
}

bool TestMgrDataOrmData::_OnEncode(KERNEL_NS::LibStream<KERNEL_NS::_Build::MT> &stream) const
{
    return _ormRawPbData->Encode(stream);
}

bool TestMgrDataOrmData::_OnEncode(KERNEL_NS::LibStream<KERNEL_NS::_Build::TL> &stream) const
{
    return _ormRawPbData->Encode(stream);
}

bool TestMgrDataOrmData::_OnDecode(KERNEL_NS::LibStream<KERNEL_NS::_Build::MT> &stream)
{
    return _ormRawPbData->Decode(stream);
}

bool TestMgrDataOrmData::_OnDecode(KERNEL_NS::LibStream<KERNEL_NS::_Build::TL> &stream)
{
    return _ormRawPbData->Decode(stream);
}

IOrmData *TestMgrDataOrmDataFactory::Create() const
{
    return TestMgrDataOrmData::NewThreadLocal_TestMgrDataOrmData();
}


SERVICE_COMMON_END
