/*!
*  MIT License
*  
*  Copyright (c) 2020 ericyonng<120453674@qq.com>
*  
*  Permission is hereby granted, free of charge, to any person obtaining a copy
*  of this software and associated documentation files (the "Software"), to deal
*  in the Software without restriction, including without limitation the rights
*  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*  copies of the Software, and to permit persons to whom the Software is
*  furnished to do so, subject to the following conditions:
*  
*  The above copyright notice and this permission notice shall be included in all
*  copies or substantial portions of the Software.
*  
*  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
*  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
*  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
*  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
*  SOFTWARE.
* 
* Author: Eric Yonng
* Description: Generated By protogentool, Dont Modify This File!!!
*/


    static constexpr Int32 OPCODE_BEGIN = 0;
    static constexpr Int32 SendDataRequest = 1;    // broadcast_msg.proto
    static constexpr Int32 SendDataResponse = 2;    // broadcast_msg.proto
    static constexpr Int32 BroadcastSendDataNty = 3;    // broadcast_msg.proto
    static constexpr Int32 BroadcastSendDataConfirmResponse = 4;    // broadcast_msg.proto
    static constexpr Int32 NodeHeartbeatReq = 5;    // heartbeat.proto
    static constexpr Int32 NodeHeartbeatRes = 6;    // heartbeat.proto
    static constexpr Int32 RegisterNodeReq = 7;    // heartbeat.proto
    static constexpr Int32 RegisterNodeRes = 8;    // heartbeat.proto
    static constexpr Int32 GetNodeListReq = 9;    // heartbeat.proto
    static constexpr Int32 GetNodeListRes = 10;    // heartbeat.proto
    static constexpr Int32 ClientHeartbeatReq = 11;    // heartbeat.proto
    static constexpr Int32 ClientHeartbeatRes = 12;    // heartbeat.proto
    static constexpr Int32 BookBagInfoReq = 13;    // bookbag.proto
    static constexpr Int32 BookBagInfoNty = 14;    // bookbag.proto
    static constexpr Int32 BookBagInfoRes = 15;    // bookbag.proto
    static constexpr Int32 SetBookBagInfoReq = 16;    // bookbag.proto
    static constexpr Int32 SetBookBagInfoRes = 17;    // bookbag.proto
    static constexpr Int32 SubmitBookBagBorrowInfoReq = 18;    // bookbag.proto
    static constexpr Int32 SubmitBookBagBorrowInfoRes = 19;    // bookbag.proto
    static constexpr Int32 GetLibraryInfoReq = 20;    // library.proto
    static constexpr Int32 LibraryInfoNty = 21;    // library.proto
    static constexpr Int32 GetLibraryInfoRes = 22;    // library.proto
    static constexpr Int32 CreateLibraryReq = 23;    // library.proto
    static constexpr Int32 CreateLibraryRes = 24;    // library.proto
    static constexpr Int32 JoinLibraryReq = 25;    // library.proto
    static constexpr Int32 JoinLibraryRes = 26;    // library.proto
    static constexpr Int32 QuitLibraryReq = 27;    // library.proto
    static constexpr Int32 QuitLibraryRes = 28;    // library.proto
    static constexpr Int32 GetLibraryListReq = 29;    // library.proto
    static constexpr Int32 GetLibraryListRes = 30;    // library.proto
    static constexpr Int32 TransferLibraianReq = 31;    // library.proto
    static constexpr Int32 TransferLibraianRes = 32;    // library.proto
    static constexpr Int32 ModifyMemberInfoReq = 33;    // library.proto
    static constexpr Int32 ModifyMemberInfoRes = 34;    // library.proto
    static constexpr Int32 UserLibraryInfoNty = 35;    // library.proto
    static constexpr Int32 GetLibraryMemberSimpleInfoReq = 36;    // library.proto
    static constexpr Int32 GetLibraryMemberSimpleInfoRes = 37;    // library.proto
    static constexpr Int32 AddLibraryBookReq = 38;    // library.proto
    static constexpr Int32 AddLibraryBookRes = 39;    // library.proto
    static constexpr Int32 AddLibraryBookCountReq = 40;    // library.proto
    static constexpr Int32 AddLibraryBookCountRes = 41;    // library.proto
    static constexpr Int32 GetBookListReq = 42;    // library.proto
    static constexpr Int32 BookListNty = 43;    // library.proto
    static constexpr Int32 BooksChangeNty = 44;    // library.proto
    static constexpr Int32 BookVariantInfoItemsNty = 45;    // library.proto
    static constexpr Int32 GetBookListRes = 46;    // library.proto
    static constexpr Int32 GetBookInfoReq = 47;    // library.proto
    static constexpr Int32 GetBookInfoRes = 48;    // library.proto
    static constexpr Int32 GetBookByBookNameReq = 49;    // library.proto
    static constexpr Int32 GetBookByBookNameRes = 50;    // library.proto
    static constexpr Int32 GetBookInfoListReq = 51;    // library.proto
    static constexpr Int32 GetBookInfoListRes = 52;    // library.proto
    static constexpr Int32 GetBookOrderDetailInfoReq = 53;    // library.proto
    static constexpr Int32 GetBookOrderDetailInfoNty = 54;    // library.proto
    static constexpr Int32 GetBookOrderDetailInfoRes = 55;    // library.proto
    static constexpr Int32 OutStoreOrderReq = 56;    // library.proto
    static constexpr Int32 OutStoreOrderRes = 57;    // library.proto
    static constexpr Int32 ManagerScanOrderForUserGettingBooksReq = 58;    // library.proto
    static constexpr Int32 UserGetBooksOrderConfirmNty = 59;    // library.proto
    static constexpr Int32 ManagerScanOrderForUserGettingBooksRes = 60;    // library.proto
    static constexpr Int32 UserGetBooksOrderConfirmReq = 61;    // library.proto
    static constexpr Int32 UserGetBooksOrderConfirmRes = 62;    // library.proto
    static constexpr Int32 CancelOrderReq = 63;    // library.proto
    static constexpr Int32 CancelOrderRes = 64;    // library.proto
    static constexpr Int32 ReturnBackReq = 65;    // library.proto
    static constexpr Int32 ReturnBackRes = 66;    // library.proto
    static constexpr Int32 UserNotifyDataNty = 67;    // notify.proto
    static constexpr Int32 UserNotifyChangeNty = 68;    // notify.proto
    static constexpr Int32 AddUserNotifyDataItemNty = 69;    // notify.proto
    static constexpr Int32 RemoveUserNotifyDataItemNty = 70;    // notify.proto
    static constexpr Int32 ReadNotifyReq = 71;    // notify.proto
    static constexpr Int32 ReadNotifyRes = 72;    // notify.proto
    static constexpr Int32 OnekeyClearNotifyReq = 73;    // notify.proto
    static constexpr Int32 OnekeyClearNotifyRes = 74;    // notify.proto
    static constexpr Int32 SystemLogDataListReq = 75;    // syslog.proto
    static constexpr Int32 SystemLogDataListRes = 76;    // syslog.proto
    static constexpr Int32 LoginReq = 77;    // login.proto
    static constexpr Int32 LoginRes = 78;    // login.proto
    static constexpr Int32 LoginInfoNty = 79;    // login.proto
    static constexpr Int32 LogoutReq = 80;    // login.proto
    static constexpr Int32 LogoutNty = 81;    // login.proto
    static constexpr Int32 LoginFinishReq = 82;    // login.proto
    static constexpr Int32 LoginFinishRes = 83;    // login.proto
    static constexpr Int32 PlayerDataReq = 84;    // player.proto
    static constexpr Int32 PlayerDataRes = 85;    // player.proto
    static constexpr Int32 ModifyPlayerNameReq = 86;    // player.proto
    static constexpr Int32 ModifyPlayerNameRes = 87;    // player.proto
    static constexpr Int32 PlayerDataNty = 88;    // player.proto
    static constexpr Int32 RpcReq = 89;    // rpc.proto
    static constexpr Int32 RpcRes = 90;    // rpc.proto
    static constexpr Int32 TestOpcodeReq = 91;    // test_opcode.proto
    static constexpr Int32 TestOpcodeRes = 92;    // test_opcode.proto
    static constexpr Int32 TestOpcode2Req = 93;    // test_opcode.proto
    static constexpr Int32 TestOpcode2Res = 94;    // test_opcode.proto
    static constexpr Int32 TestRpcReq = 95;    // test_opcode.proto
    static constexpr Int32 TestRpcRes = 96;    // test_opcode.proto
    static constexpr Int32 TitleInfoReq = 97;    // title.proto
    static constexpr Int32 TitleInfoRes = 98;    // title.proto
    static constexpr Int32 UserClientInfoNty = 99;    // user.proto
    static constexpr Int32 ModifyUserInfoReq = 100;    // user.proto
    static constexpr Int32 ModifyUserInfoRes = 101;    // user.proto
    static constexpr Int32 OPCODE_MAX = 101;
